### ISSUE TITLE
nice scripts but how to uninstall 

### ISSUE THREAD

**Issue by trinib** [farag2/Windows-10-Sophia-Script#100]
im satiified with project but how to uninstall just in case

**Comment by farag2** [comment]
Uninstall what?

**Comment by trinib** [comment]
> 
> 
> Uninstall what?

revert scripts and settings to default ...is there any method for that ?

**Comment by farag2** [comment]
Of course there is! Read the preset file carefully!
https://github.com/farag2/Windows-10-Sophia-Script#%EF%B8%8F-before-running-%EF%B8%8F

**Comment by trinib** [comment]
> 
> 
> Of course there is! Read the preset file carefully!
> https://github.com/farag2/Windows-10-Sophia-Script#%EF%B8%8F-before-running-%EF%B8%8F
> 
> All functions for reverting are commented out.

oh my bad ..though that was just for choosing what to enable only ..didnt know commenting out line will disable 

Nice update for 20h2 thanks for the work

**Comment by farag2** [comment]
You are welcome! Wait for the 5.3 release next week.
