### ISSUE TITLE
error when running a .bat file

### ISSUE THREAD

**Issue by trinib** [farag2/Windows-10-Sophia-Script#101]
i dont what causes this ..i already have "windows host scipt" in registry enabled
![image](https://user-images.githubusercontent.com/18756975/101708381-860b6880-3a63-11eb-9283-e61fea6f812c.png)

**Comment by trinib** [comment]
ok just needed to search text in file for host disable part lol ..nooby

**Comment by farag2** [comment]
Ar!
https://github.com/farag2/Windows-10-Sophia-Script/blob/58bcb4f75414ee8afc8f821517b41c449d1ce1c2/Sophia/Sophia.ps1#L1099

Read the preset file first!
So to enable it ran just this line:
https://github.com/farag2/Windows-10-Sophia-Script/blob/58bcb4f75414ee8afc8f821517b41c449d1ce1c2/Sophia/Sophia.psm1#L8247

**Comment by trinib** [comment]
im stuck here
![image](https://user-images.githubusercontent.com/18756975/102077639-0291a480-3de0-11eb-8d80-a10efe15e370.png)

**Comment by farag2** [comment]
Ok. I'll do some test.

**Comment by farag2** [comment]
Fixed. Redownload all archive. Localizations were updated too.

**Comment by trinib** [comment]
working ✌

**Comment by farag2** [comment]
:feelsgood:

**Comment by trinib** [comment]
i have startisback and script hangs after adding pinned shortcuts but i saw on little text on powerhell while its executing "hold down escape to prevent startisback from loading" and i did that and ran smoothly ....just for some1 who has this issue :)

**Comment by farag2** [comment]
The syspin using is not designed to be applied to an OS with StartIsBack. As for me I prefer pure Win 10 Start. So))

**Comment by trinib** [comment]
> 
> 
> The syspin using is not designed to be applied to an OS with StartIsBack. As for me I prefer pure Win 10 Start. So))

not a prob for me ..as long it had a fix

**Comment by farag2** [comment]
Didn't get. What kind of fix?..

**Comment by trinib** [comment]
> 
> 
> Didn't get. What kind of fix?..

well not a fix specifically...just to bypass the part i was stuck/hangs due to startisback ..all good

**Comment by farag2** [comment]
OK. :trollface:
