### ISSUE TITLE
Script ignores my imput for temp files delete...

### ISSUE THREAD

**Issue by aconetwork** [farag2/Windows-10-Sophia-Script#102]
First I want to thank you for the script 😁

Okay. I ran the Sophia script version 5.3 on Windows 10 20H2 and when it comes to temp files delete, if I skip OR delete and then skip (when some files are locked by some other app - script said) it just circles back to beggining of temp files deletion even when I confirm S for skip, it says that it is skipped, but I could not proceed foward.

**Comment by farag2** [comment]
Thank you)
I've already fixed this yesterday and uploaded a new vesion.
Redownload the archive!
https://github.com/farag2/Windows-10-Sophia-Script/issues/101#issuecomment-744385383

**Comment by aconetwork** [comment]
Thank you 😁

**Comment by farag2** [comment]
All OK?

**Comment by aconetwork** [comment]
Will try it in next 12 hours and I will let you know 😁
