### ISSUE TITLE
Line missing to unpin Edge in latest version

### ISSUE THREAD

**Issue by bigbadmoshe** [farag2/Windows-10-Sophia-Script#104]
$Apps | Where-Object -FilterScript {$_.Path -eq "MSEdge"} | ForEach-Object -Process {$_.Verbs() | Where-Object -FilterScript {$_.Name -eq $LocalizedString} | ForEach-Object -Process {$_.DoIt()}}

Taken from older script.

Sophia 5.3.1
Regular powershell and 7.1 scripts.

**Comment by farag2** [comment]
It wasn't missed. MS disallow to unpin the new Edge programmatically...

**Comment by bigbadmoshe** [comment]
Thanks for prompt reply

**Comment by farag2** [comment]
You can try it by yourself. Pin the new Edge and run this.

```powershell
$Apps = (New-Object -ComObject Shell.Application).NameSpace("shell:::{4234d49b-0245-4df3-b780-3893943456e1}").Items()
$Apps | Where-Object -FilterScript {$_.Path -eq "MSEdge"} | ForEach-Object -Process {$_.Verbs()}
```

There is no more "the unpin from Taskbar" string.
