### ISSUE TITLE
[Privacy] Disable: "Let Windows track app launches to improve Start and search results"

### ISSUE THREAD

**Issue by guihkx** [farag2/Windows-10-Sophia-Script#106]
This option is found in Settings and is enabled by default (tested only on Windows 10 20H2):

![image](https://user-images.githubusercontent.com/626206/102931864-f5c71d80-447d-11eb-9f9b-7a0764ce9a5b.png)

To disable this option:

```
New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name Start_TrackProgs -PropertyType DWord -Value 0 -Force
```

To enable it:

```
New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name Start_TrackProgs -PropertyType DWord -Value 1 -Force
```

Thanks!

**Comment by farag2** [comment]
I know about it. But I cannot recall why I removed this from the script. Seems it breaks something in Windows.

**Comment by guihkx** [comment]
Oh, that's odd... Thanks for the info, though :)

On a completely unrelated note: Are you aware of this project:

https://github.com/Disassembler0/Win10-Initial-Setup-Script/

It's unmaintained now, but I believe it might have some tweaks that Sophia doesn't (e.g. disable Windows Defender)

**Comment by farag2** [comment]
> Are you aware
For sure I do. :) A nice one. Someday I started scripting  with an eye to this project. Much water has passed under the bridge since that time... Only my project and AutoSettingsPS left.

> Some tweaks that Sophia doesn't
If users wants to finish off his OS, I won't be in their road, but I will never provide such destructive tweaks.

P.S. Had to google to translate into English "to be in the smb.'s road": could only recall "bother". Russian is much easier in that respect. :)

**Comment by guihkx** [comment]
Hahahaha, I figured you wouldn't want to add those... :( 

No problem, though.

Another unrelated question (it's the last one, I promise 😆): I couldn't find a tweak in Sophia would disable this "Show suggestions in your timeline" setting under **Multitasking**:

![image](https://user-images.githubusercontent.com/626206/102934236-84d63480-4482-11eb-892d-2cc5c4c510d9.png)

I would send a pull request to add this tweak, but my Russian is a bit rusty (😉), so I wouldn't be able to write a description for this new tweak in Russian.

Anyway, here's the tweak itself:

To disable the option:

```
New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name SubscribedContent-353698Enabled -PropertyType DWord -Value 0 -Force
```

To enable it again (default):

```
New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name SubscribedContent-353698Enabled -PropertyType DWord -Value 1 -Force
```

**Comment by farag2** [comment]
I can write a code if you want to add, but don't think it'll be the right way to add this stuff.

More to say: you cannot disable Defender via console (and I agree with MS). Fed up with kiddie scripters in that push this kind of "tweak".
Security, hello! I'm OK, but cannot say about "my" OS that was fucked by a ransomeware.

**Comment by guihkx** [comment]
Well, I do believe there are use cases in which that option could be useful, but I don't want to impose anything on you, it was merely a suggestion.

>you cannot disable Defender via console

Indeed. IIRC, nowadays you have to first disable Windows Defender's "Tamper Protection" in order to disable everything else via scripting.

>Fed up with kiddie scripters in that push this kind of "tweak".

Hahahah, I get where you coming from, but I've been disabling their antivirus forever, because:

* I use Linux as my daily driver, so the only rare times I use Windows 10, is when I want to play some CS:GO
* In my experience, having the MS antivirus enabled while gaming, absolutely shits on its performance (and CPU usage increases in general as well)
* I rarely install stuff when I'm on Windows, and when I do, it's always from trusted sources (i.e. I don't pirate stuff)
* If somehow my Windows get fucked in the ass by a ransomware, it's not a big deal for me particularly, because I do regular online backups of my critical stuff.
* Antiviruses collect more data than anything else, so in my opinion disabling them is a matter of enhanced privacy more than anything else. lol

**Comment by farag2** [comment]
```powershell
<#
	.SYNOPSIS
	Disable/enable the Timeline Suggestions in Timeline

	.PARAMETER Disable
	Disable the Timeline Suggestions in Timeline

	.PARAMETER Enable
	Enable the Timeline Suggestions in Timeline

	.EXAMPLE
	TimelineSuggestions -Disable

	.EXAMPLE
	TimelineSuggestions -Enable

	.NOTES
	Current user only
#>
function TimelineSuggestions
{
	param
	(
		[Parameter(
			Mandatory = $true,
			ParameterSetName = "Enable"
		)]
		[switch]
		$Enable,

		[Parameter(
			Mandatory = $true,
			ParameterSetName = "Disable"
		)]
		[switch]
		$Disable
	)

	switch ($PSCmdlet.ParameterSetName)
	{
		"Enable"
		{
			New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name SubscribedContent-353698Enabled -PropertyType DWord -Value 1 -Force
		}
		"Disable"
		{
			New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager -Name SubscribedContent-353698Enabled -PropertyType DWord -Value 0 -Force
		}
	}
}
```
