### ISSUE TITLE
Windows Server 2019 support

### ISSUE THREAD

**Issue by bhonushriram** [farag2/Windows-10-Sophia-Script#110]
Can you please add Windows Server 2019 support in Sophia script?

**Comment by farag2** [comment]
Why you want to fine-tune this kind of OS. It's designed not for home using. It's from an enterpise area. Every enterprise admin can customize my script to fit his needs.
Also: https://github.com/farag2/Windows-10-Sophia-Script/discussions/109

**Comment by bhonushriram** [comment]
> Why you want to fine-tune this kind of OS. It's designed not for home using. It's from an enterpise area. Every enterprise admin can customize my script to fit his needs.
> Also: #109

Thank you for your reply

Actually I am using this for my employee for office use it is cloud base workstation and want to improve performace and want to do fine tunning for them.

**Comment by farag2** [comment]
Were did the myth come from that my script (or similar) boosts performance? :) It doesn't not. It only can fine-tune the OS.
So as I mentioned before remove the check or change the build number to let the script pass it.
