### ISSUE TITLE
Integrate some privacy related settings

### ISSUE THREAD

**Issue by gavenkoa** [farag2/Windows-10-Sophia-Script#115]
Following repository has interesting privacy settings:

https://github.com/aghorler/Windows-10-Hardening/blob/master/components/group_policy.bat

Some of them (check link for more & details):

```
RestrictImplicitInkCollection
RestrictImplicitTextCollection
PreventHandwritingErrorReports
PreventHandwritingDataSharing
AllowInputPersonalization
RestrictImplicitInkCollection
RestrictImplicitTextCollection
PreventHandwritingErrorReports
PreventHandwritingDataSharing

PolicyDisableGeolocation
DisableLogging

DisableCustomerImprovementProgram
```

**Comment by farag2** [comment]
Спасибо, конечно, но как раз хочу максимально отойти от метода использования политик. Тут не энтерпрайз.
