### ISSUE TITLE
Consider to not only disable feature but also close related firewall rule

### ISSUE THREAD

**Issue by gavenkoa** [farag2/Windows-10-Sophia-Script#116]
I find idea of disabling firewall rules appealing. If some registry settings are stopped to been obeyed firewall says fuck to Microsoft.

For example:

```
netsh advfirewall firewall show rule name=Cortana
netsh advfirewall firewall show rule name=DiagTrack
```

Some examples can be found here:

https://github.com/aghorler/Windows-10-Hardening/blob/master/components/firewall.bat

**Comment by farag2** [comment]
Опять же нет: админы итак знают, что делать, а пользователи лишь все сломают.

**Comment by gavenkoa** [comment]
OK )) If any:

```
Get-NetFirewallRule -Group Cortana | Set-NetFirewallRule -Enabled False
Get-NetFirewallRule -Group DiagTrack | Set-NetFirewallRule -Enabled False
```

**Comment by farag2** [comment]
А у меня пусто

```powershell
Get-NetFirewallRule -DisplayName "Cortana"
```

Почему?..
