### ISSUE TITLE
user account

### ISSUE THREAD

**Issue by trinib** [farag2/Windows-10-Sophia-Script#117]
hi user account cannot be opened in control panel

**Comment by farag2** [comment]
Hello. Everything works fine. Something has gone wrong with your OS. And cannot be script fault. It's just a shortcut.

**Comment by trinib** [comment]
ok ..i cant upload a screenshot of anything ,,i gues si need to re in stall windows

**Comment by farag2** [comment]
Why you can't?

> i gues si need to re in stall windows
Seems so...

**Comment by farag2** [comment]
Did you try

`DISM /Online /Cleanup-Image /RestoreHealth`

and then

`sfc /scannow`

?

**Comment by trinib** [comment]
> 
> 
> Why you can't?
> 
> > i gues si need to re in stall windows
> > Seems so...
> 
> Also why do you need to open this applet? There is the same applet in the Settings app.
 not change uac control

**Comment by farag2** [comment]
Try to type "uac" in the search bat in the Settings app. It can be opened from there.

**Comment by trinib** [comment]
> 
> 
> Try to type "uac" in the search bat in the Settings app. It can be opened from there. And don't forget to repair Windows

well this is embarrassing ..only because my pc name was 👽👽👽👽👽👽 i could not get in my user account in control panel and also was getting a error in a program about uft-16 error .....damn , blame it on the scipt lol 😂🤣

**Comment by farag2** [comment]
It seems, I've seen all after this. :)
