### ISSUE TITLE
LTSC support

### ISSUE THREAD

**Issue by methanoid** [farag2/Windows-10-Sophia-Script#118]
Since the previous report was closed without resolution, 

Please clarify - is LTSC ONLY supported in 5.0 script and none of scripts since then work with LTSC?

**Comment by farag2** [comment]
I've added LTSC support some days ago (without a new release). Just attached a new zip archive.
https://github.com/farag2/Windows-10-Sophia-Script#supported-windows-10-versions
https://github.com/farag2/Windows-10-Sophia-Script/releases/latest
