### ISSUE TITLE
Want to run specific script, what I do wrong?

### ISSUE THREAD

**Issue by necros2k7** [farag2/Windows-10-Sophia-Script#119]
powershell New-ItemProperty -Path Registry::HKEY_CLASSES_ROOT\Drive\shell\encrypt-bde -Name ProgrammaticAccessOnly -PropertyType String -Value "" -Force
New-ItemProperty : Отсутствует аргумент для параметра "Value". Укажите параметр типа "System.Object" и повторите попытк
у.
строка:1 знак:126
+ ... -bde -Name ProgrammaticAccessOnly -PropertyType String -Value  -Force
+                                                            ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ItemProperty], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Microsoft.PowerShell.Commands.NewItemPropertyCommand

**Comment by farag2** [comment]
А зачем удалял в шаблоне все те пункты, которые нужные для определения билда, редакции? Верни все, оформи, как положено, тогда будем разбираться.

**Comment by farag2** [comment]
Если не пришлешь, я завтра закрою.
