### ISSUE TITLE
installing on a kvm vm causes that vm to be unbootable

### ISSUE THREAD

**Issue by irockdude554** [farag2/Windows-10-Sophia-Script#120]
Before submitting a bug report:

### Prerequisites

* Make sure you are able to reproduce it on the latest released version;
* [x] Verify that this is not a Windows issue;
* [x] Check the [**Before running**](https://github.com/farag2/Windows-10-Sophia-Script#fire-before-running-fire) & [**Usage**](https://github.com/farag2/Windows-10-Sophia-Script#usage) sections

**Steps to reproduce**
------------------
install windows in a fresh vm
extract sophia and script and the gui 
change settings and then click run powershell
script runs just fine but when i reboot the vm its no longer bootable
this script used to work under a kvm vm before so im not sure why it bricks a vm now
```PowerShell

```

**Screenshots**

**Desktop (please complete the following information):**
- Windows build (**winver**): [e.g. 19042]
windows 10 2004 64bit
**Additional context**

**Comment by farag2** [comment]
Hello! As far as I understand it, I need to install KVM on Linux based OS?

**Comment by irockdude554** [comment]
yes, use whatever linux os your comfortable with and then setup amd/intel iommu groups and then passthrough your gpu and install ovmf,libvirt,qemu and lib-virt-manager this is to get as close to bare metal peformance as possible on the vm

**Comment by farag2** [comment]
Unfortunately I have no free PC to test on. May be I can connect to you via for example TeamViewer and we'see what's going on?

**Comment by irockdude554** [comment]
sure ill make a new vm so you can see what it does

**Comment by farag2** [comment]
It's now 11:11 am MSK. DM me in Discord: sanctuary_s#6351

**Comment by irockdude554** [comment]
Ok, I sent you a friend request.

**Comment by farag2** [comment]
Accepted.

**Comment by farag2** [comment]
The cause was the WindowsSandbox function.
https://github.com/farag2/Windows-10-Sophia-Script/blob/db045e96b1d43ec32f4e75ef4436b4aa93209665/Sophia/Sophia.psm1#L9422
