### ISSUE TITLE
The full changelog for all years can be found here.

### ISSUE THREAD

**Issue by Xclio** [farag2/Windows-10-Sophia-Script#123]
по почте приходит в рассылке
The full changelog for all years can be found here.
но here - https://github.com/farag2/Windows-10-Sophia-Script/blob/master/Changelog.md
ведет в нарнию )

**Comment by farag2** [comment]
Меня тоже в Хуярнию отправило. Case sensetive, оказывается. Исправил ссылку. Но рассылку не вернуть...

**Comment by Xclio** [comment]
ну и ладно, на будущее значит )

**Comment by farag2** [comment]
Пересоздал. Как оно?

**Comment by Xclio** [comment]
теперь всё ок

**Comment by Xclio** [comment]
да я фиг его знает зачем, мне только подписка об обновлениях была нужна. я и не заходил сюда с тех пор )

**Comment by Xclio** [comment]
как его удалить то теперь 0_о

**Comment by farag2** [comment]
Да ты хакер!

![Image](https://www.pinclipart.com/picdir/big/349-3493479_free-plan-emoji-hacker-png-clipart.png)

> как его удалить то теперь 0_о

**Comment by Xclio** [comment]
о да )) 

ура )

**Comment by farag2** [comment]
Я тут давеча тоже хакера видел на GH: смотрю, а него аж 70 репозиториев. А потом сделал фильтр на "Source", и выяснилось, что собственных у него 4. Пустых. :) неужели работодатели ведутся?..

**Comment by Xclio** [comment]
да фиг знает ) это не моя тема ) я, наверное, куда-то не туда отверткой ткнул ))
