### ISSUE TITLE
CreateRestorePoint enables Restore points even when disabled

### ISSUE THREAD

**Issue by Cubox** [farag2/Windows-10-Sophia-Script#124]
Hi,

It seems that the Wrapper will always output CreateRestorePoint in the generated powershell. Since I manually disable those, I don't want restore points created.
The issue is that Sophia will enable restore points again, https://github.com/farag2/Windows-10-Sophia-Script/blob/2ce62a3cf64b859814a30e435df086d4b170aa6d/Sophia/Sophia.psm1#L130

Could Sophia either not overwrite the previously configured restore point, or the Wrapper let us pick if we want to create a restore point?
Maybe there is an option to do this already, and I'm missing it...

Running 21.01.2021

**Comment by farag2** [comment]
Did you disable this function?
https://github.com/farag2/Windows-10-Sophia-Script/blob/2ce62a3cf64b859814a30e435df086d4b170aa6d/Sophia/Sophia.ps1#L88

**Comment by Cubox** [comment]
The wrapper generates this script. Sure, you can comment it, but if you're not paying attention, you don't see Sophia enabling system restore points "behind your back"

**Comment by farag2** [comment]
Hm, I'll update this function.

**Comment by Cubox** [comment]
Thanks!
Love the script, I'll contribute some functions from tips I apply on my installs

**Comment by farag2** [comment]
https://github.com/farag2/Windows-10-Sophia-Script/releases/tag/5.4
