### ISSUE TITLE
Should I run the script before or after user creation?

### ISSUE THREAD

**Issue by farinelli123** [farag2/Windows-10-Sophia-Script#126]
Hi @farag2 ! Hope you're doing well. Thanks for this amazing script.
My dad uses sometimes my pc so I have to create an exclusive user for him. 
Should I run your script before or after doing that?
Best regards!

**Comment by farag2** [comment]
Hi! After user creation of course. Most of the settings are being applied for current user.

**Comment by farinelli123** [comment]
Thank you so much!
