### ISSUE TITLE
uh its just stuck at something and idk what to do

### ISSUE THREAD

**Issue by yurixoxo** [farag2/Windows-10-Sophia-Script#128]
im very new sorry for asking this probably newbie question  but so idk like everything was running smooth for a bit and now it sort of stopped and idk if its done or not the  last thing powershell said was 

10670 Sophia.psm1 Unable to find type [WinAPI.UpdateExplorer].

thank you <3

**Comment by farag2** [comment]
> Joined 9 minutes ago

:3

Your OS build?

> Unable to find type [WinAPI.UpdateExplorer]

Seems, you didnt import module... But idk how it could happen. I better need to see by myself what have gone wrong. May be via teamviewer or similar.

**Comment by yurixoxo** [comment]
windows 10 latest build 

please thank you so much yurixoxo#0404 i am installing tv now i am on kinda fresh windows 10 reset so barely have anything set up

**Comment by yurixoxo** [comment]
oh thats discord btw

**Comment by farag2** [comment]
write to me on Discord if you have: @sanctuary_s#6351

**Comment by yurixoxo** [comment]
haha ok thank you!

**Comment by farag2** [comment]
Anyway, aftee what I've seen on your PC, strongly advise to reinstall the OS. :)

**Comment by yurixoxo** [comment]
yeah, i literally installed fresh windows 10 a couple days ago but i found some bad powershell script for on github.. it was called like windows debloater i think idk it was a mess... 

when i reset windows, ill make sure im offline so it doesnt force too many bad drivers, and software, or should i just do it normally and run sofia at the end??

**Comment by farag2** [comment]
Reinstall :). Even PowerShell was fucked up. Thanks to that shitty script.
Reinstall OS, update it until there won't be any updates, install NVidia driver via special program (to not to install telemetry, unnecessary apps with the driver), reboot, and apply the script. Don't forget to configure the preset file before applying.
If you're n00b, pm me in Discord. :)
