### ISSUE TITLE
My old .txt radiobutton file is not compatible with the latest version.

### ISSUE THREAD

**Issue by mikhoul** [farag2/Windows-10-Sophia-Script#129]
My old .txt file is not compatible with the latest version:

![image](https://user-images.githubusercontent.com/5678673/106952039-9146e180-66fe-11eb-9a29-a1dc84437de3.png)

Could you tell me what to do/change to make it compatible ?

Regards  :octocat: 

[RadioButtonsSophia.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928358/RadioButtonsSophia.txt)

**Comment by farag2** [comment]
sec...

**Comment by mikhoul** [comment]
> sec...

What is the meaning of "sec.."   ?   🤔

**Comment by farag2** [comment]
> What is the meaning of "sec.." ? 🤔

In Russian it means "wait for a moment", like second ))

**Comment by farag2** [comment]
Well. I'm not the wrapper developer but here it's fixed version. Just open 2 files in Beyound Compare :)
Changed `UninstallOneDrive` to `OneDrive -Uninstall`, `InstallHEVC` to `InstallHEIF`

[RadioButtonsSophia.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928397/RadioButtonsSophia.txt)

**Comment by mikhoul** [comment]
Thanks a lot !   :+1:

**Comment by farag2** [comment]
Works?)

**Comment by mikhoul** [comment]
Oups !!!!   No I assumed it would work but I receive the same Error pop-up sadly.

**Comment by farag2** [comment]
Send here all txt files

**Comment by mikhoul** [comment]
[data.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928468/data.txt)
[default.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928469/default.txt)
[tooltip.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928470/tooltip.txt)
[RadioButtonsSophia.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928473/RadioButtonsSophia.txt)

**Comment by farag2** [comment]
It works. It hasnt been working because `<#systemprotection#>` need in the begining of the file.

[RadioButtonsSophia.txt](https://github.com/farag2/Windows-10-Sophia-Script/files/5928540/RadioButtonsSophia.txt)

**Comment by mikhoul** [comment]
It work !    Thanks a lot for the fix  👍

**Comment by farag2** [comment]
:rocket:
At last I can take a sleep :)
