### ISSUE TITLE
Error while running the power shell

### ISSUE THREAD

**Issue by benzntech** [farag2/Windows-10-Sophia-Script#130]
Import-Module : The specified module 'C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.psd1'
was not loaded because no valid module file was found in any module directory.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:4 char:1
+ Import-Module -Name $PSScriptRoot\Sophia.psd1 -PassThru -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\BNB\Do...per\Sophia.psd1:String) [Import-Module], FileNot
   FoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-LocalizedData : Cannot find the Windows PowerShell data file 'Sophia.psd1' in directory
'C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\en-US\', or in any parent culture directories.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:5 char:1
+ Import-LocalizedData -BindingVariable Global:Localization -FileName S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\BNB\Do...-US\Sophia.psd1:String) [Import-LocalizedData], PSInv
   alidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData

Checkings : The term 'Checkings' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:6 char:1
+ Checkings
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Checkings:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

LeaveAlone : The term 'LeaveAlone' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:10 char:1
+ LeaveAlone
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LeaveAlone:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DiagnosticDataLevel : The term 'DiagnosticDataLevel' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:14 char:1
+ DiagnosticDataLevel -Minimal
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DiagnosticDataLevel:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ErrorReporting : The term 'ErrorReporting' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:15 char:1
+ ErrorReporting -Disable
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ErrorReporting:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WindowsFeedback : The term 'WindowsFeedback' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:16 char:1
+ WindowsFeedback -Disable
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WindowsFeedback:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ScheduledTasks : The term 'ScheduledTasks' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:17 char:1
+ ScheduledTasks -Disable
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ScheduledTasks:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

SigninInfo : The term 'SigninInfo' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:18 char:1
+ SigninInfo -Disable
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SigninInfo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

LanguageListAccess : The term 'LanguageListAccess' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:19 char:1
+ LanguageListAccess -Disable
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (LanguageListAccess:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

AdvertisingID : The term 'AdvertisingID' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:20 char:1
+ AdvertisingID -Disable
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AdvertisingID:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ShareAcrossDevices : The term 'ShareAcrossDevices' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:21 char:1
+ ShareAcrossDevices -Disable
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ShareAcrossDevices:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WindowsWelcomeExperience : The term 'WindowsWelcomeExperience' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:22 char:1
+ WindowsWelcomeExperience -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WindowsWelcomeExperience:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WindowsTips : The term 'WindowsTips' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:23 char:1
+ WindowsTips -Enable
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WindowsTips:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

SettingsSuggestedContent : The term 'SettingsSuggestedContent' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:24 char:1
+ SettingsSuggestedContent -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SettingsSuggestedContent:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

AppsSilentInstalling : The term 'AppsSilentInstalling' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:25 char:1
+ AppsSilentInstalling -Disable
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppsSilentInstalling:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WhatsNewInWindows : The term 'WhatsNewInWindows' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:26 char:1
+ WhatsNewInWindows -Disable
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WhatsNewInWindows:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

TailoredExperiences : The term 'TailoredExperiences' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:27 char:1
+ TailoredExperiences -Disable
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TailoredExperiences:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

BingSearch : The term 'BingSearch' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:28 char:1
+ BingSearch -Disable
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (BingSearch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ThisPC : The term 'ThisPC' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:32 char:1
+ ThisPC -Show
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (ThisPC:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

CheckBoxes : The term 'CheckBoxes' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:33 char:1
+ CheckBoxes -Disable
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CheckBoxes:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

HiddenItems : The term 'HiddenItems' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:34 char:1
+ HiddenItems -Enable
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HiddenItems:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

FileExtensions : The term 'FileExtensions' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:35 char:1
+ FileExtensions -Show
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FileExtensions:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

MergeConflicts : The term 'MergeConflicts' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:36 char:1
+ MergeConflicts -Show
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MergeConflicts:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

OpenFileExplorerTo : The term 'OpenFileExplorerTo' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:37 char:1
+ OpenFileExplorerTo -ThisPC
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OpenFileExplorerTo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

CortanaButton : The term 'CortanaButton' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:38 char:1
+ CortanaButton -Hide
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CortanaButton:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

OneDriveFileExplorerAd : The term 'OneDriveFileExplorerAd' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:39 char:1
+ OneDriveFileExplorerAd -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OneDriveFileExplorerAd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

TaskViewButton : The term 'TaskViewButton' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:40 char:1
+ TaskViewButton -Hide
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TaskViewButton:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PeopleTaskbar : The term 'PeopleTaskbar' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:41 char:1
+ PeopleTaskbar -Hide
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PeopleTaskbar:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

SecondsInSystemClock : The term 'SecondsInSystemClock' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:42 char:1
+ SecondsInSystemClock -Show
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SecondsInSystemClock:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

SnapAssist : The term 'SnapAssist' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:43 char:1
+ SnapAssist -Disable
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SnapAssist:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

FileTransferDialog : The term 'FileTransferDialog' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:44 char:1
+ FileTransferDialog -Detailed
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FileTransferDialog:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

FileExplorerRibbon : The term 'FileExplorerRibbon' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:45 char:1
+ FileExplorerRibbon -Expanded
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FileExplorerRibbon:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

RecycleBinDeleteConfirmation : The term 'RecycleBinDeleteConfirmation' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:46 char:1
+ RecycleBinDeleteConfirmation -Enable
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RecycleBinDeleteConfirmation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

3DObjects : The term '3DObjects' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:47 char:1
+ 3DObjects -Hide
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (3DObjects:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

QuickAccessFrequentFolders : The term 'QuickAccessFrequentFolders' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:48 char:1
+ QuickAccessFrequentFolders -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (QuickAccessFrequentFolders:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

QuickAccessRecentFiles : The term 'QuickAccessRecentFiles' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:49 char:1
+ QuickAccessRecentFiles -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (QuickAccessRecentFiles:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WindowsInkWorkspace : The term 'WindowsInkWorkspace' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:50 char:1
+ WindowsInkWorkspace -Hide
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WindowsInkWorkspace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

TrayIcons : The term 'TrayIcons' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:51 char:1
+ TrayIcons -Show
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TrayIcons:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

UnpinTaskbarEdgeStore : The term 'UnpinTaskbarEdgeStore' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:52 char:1
+ UnpinTaskbarEdgeStore
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (UnpinTaskbarEdgeStore:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ControlPanelView : The term 'ControlPanelView' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:53 char:1
+ ControlPanelView -LargeIcons
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ControlPanelView:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WindowsColorScheme : The term 'WindowsColorScheme' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:54 char:1
+ WindowsColorScheme -Dark
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (WindowsColorScheme:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

AppMode : The term 'AppMode' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:55 char:1
+ AppMode -Dark
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppMode:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

NewAppInstalledNotification : The term 'NewAppInstalledNotification' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:56 char:1
+ NewAppInstalledNotification -Hide
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (NewAppInstalledNotification:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

FirstLogonAnimation : The term 'FirstLogonAnimation' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:57 char:1
+ FirstLogonAnimation -Disable
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (FirstLogonAnimation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

JPEGWallpapersQuality : The term 'JPEGWallpapersQuality' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:58 char:1
+ JPEGWallpapersQuality -Max
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (JPEGWallpapersQuality:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

TaskManagerWindow : The term 'TaskManagerWindow' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:59 char:1
+ TaskManagerWindow -Expanded
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TaskManagerWindow:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

RestartNotification : The term 'RestartNotification' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:60 char:1
+ RestartNotification -Show
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RestartNotification:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ShortcutsSuffix : The term 'ShortcutsSuffix' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:61 char:1
+ ShortcutsSuffix -Disable
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ShortcutsSuffix:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PrtScnSnippingTool : The term 'PrtScnSnippingTool' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:62 char:1
+ PrtScnSnippingTool -Enable
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PrtScnSnippingTool:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

AppsLanguageSwitch : The term 'AppsLanguageSwitch' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:63 char:1
+ AppsLanguageSwitch -Disable
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppsLanguageSwitch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

OneDrive : The term 'OneDrive' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\BNB\Downloads\Sophia.Script.Wrapper\Sophia Script Wrapper\Sophia.ps1:67 char:1
+ OneDrive -Uninstall
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (OneDrive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by farag2** [comment]
What archives did you download from here?
https://github.com/farag2/Windows-10-Sophia-Script/releases/tag/5.4.0.1

**Comment by farag2** [comment]
So?..

**Comment by benzntech** [comment]
Yes Downloaded the latest archive !

**Comment by farag2** [comment]
So did you follow?

https://github.com/farag2/Windows-10-Sophia-Script#usage

I couldn't reproduce any errors.
