### ISSUE TITLE
Error with Delete-DeliveryOptimizationCache

### ISSUE THREAD

**Issue by mikhoul** [farag2/Windows-10-Sophia-Script#132]
Here's another the error of the same type:

![image](https://user-images.githubusercontent.com/5678673/107311195-e7e45080-6a5b-11eb-99f7-6be51e880041.png)

The function is in the psm1 file.

I'm not really proficient with Powershell do you have an idea that what could cause this error ?

Regards :octocat:

**Comment by farag2** [comment]
So Win 10 build? Because I know what these errors are about.

**Comment by mikhoul** [comment]
Windows Enterprise evaluation Version 1809 (OS Build 17763.1697).

**Comment by farag2** [comment]
And you are running LTSC script?

**Comment by farag2** [comment]
Cus I can see that this cmdlet is 2004/20H2 Win 10 versions. And you running not your script.

**Comment by farag2** [comment]
https://github.com/farag2/Windows-10-Sophia-Script#supported-windows-10-versions

**Comment by mikhoul** [comment]
> And you are running LTSC script?

No since I was thinking it was not an LTSC version because it have the Windows Store and LTSC usually don't have the Windows store.

In fact it is a VM image from Microsoft.

**Comment by farag2** [comment]
So for the LTSC version yu should use LTSC. For the current Win 10 builds (2004/20H2) you should use 5.4.0.1. Any questions? :)

**Comment by mikhoul** [comment]
No, Thanks a lot for the help !  :+1:

**Comment by farag2** [comment]
As you can see there is the cmdlet that occured the error 
https://github.com/farag2/Windows-10-Sophia-Script/blob/1edd1c401c8f263a149fa849baf1de03b162d6c6/Sophia/PowerShell%205.1/Sophia.psm1#L4189

and here there is no such cmdlet

https://github.com/farag2/Windows-10-Sophia-Script/blob/1edd1c401c8f263a149fa849baf1de03b162d6c6/Sophia/LTSC/Sophia.psm1#L3397
