### ISSUE TITLE
Null-valued expression error

### ISSUE THREAD

**Issue by bignadad** [farag2/Windows-10-Sophia-Script#134]
Before submitting a bug report:

### Prerequisites

* Make sure you are able to repro it on the latest released version;
* [*] Verify that this is not a Windows issue;
* [*] Check the [**Before running**](https://github.com/farag2/Windows-10-Sophia-Script#fire-before-running-fire) & [**Usage**](https://github.com/farag2/Windows-10-Sophia-Script#usage) sections

**Steps to reproduce**
------------------
I am running this on a domain users laptop. I am running powershell as admin. None of the changes are being done. I have tried to reboot and run again but same issue. 

```PowerShell
Clear-Host
$Host.UI.RawUI.WindowTitle = 'Windows 10 Sophia Script | Copyright farag & oZ-Zo, 2015 to 2021'
Remove-Module -Name Sophia -Force -ErrorAction Ignore
Import-Module -Name $PSScriptRoot\Sophia.psd1 -PassThru -Force
Import-LocalizedData -BindingVariable Global:Localization -FileName Sophia
Checkings

# System Protection

CreateRestorePoint

# Privacy & Telemetry


# UI and Personalization

ThisPC -Show
CheckBoxes -Disable
HiddenItems -Disable
FileExtensions -Hide
MergeConflicts -Show
OpenFileExplorerTo -ThisPC
CortanaButton -Hide
OneDriveFileExplorerAd -Hide
TaskViewButton -Hide
PeopleTaskbar -Hide
SecondsInSystemClock -Hide
SnapAssist -Disable
FileTransferDialog -Detailed
FileExplorerRibbon -Expanded
RecycleBinDeleteConfirmation -Enable
3DObjects -Hide
QuickAccessFrequentFolders -Hide
QuickAccessRecentFiles -Hide
WindowsInkWorkspace -Hide
UnpinTaskbarEdgeStore
WindowsColorScheme -Light
AppMode -Light
NewAppInstalledNotification -Hide
FirstLogonAnimation -Disable
JPEGWallpapersQuality -Max
TaskManagerWindow -Expanded
RestartNotification -Hide
ShortcutsSuffix -Disable
PrtScnSnippingTool -Enable
AppsLanguageSwitch -Disable

# OneDrive

OneDrive -Uninstall

# System


# Start

RecentlyAddedApps -Hide
AppSuggestions -Hide
PinToStart -Tiles ControlPanel
PinToStart -Tiles DevicesPrinters
PinToStart -UnpinAll

# UWP

CortanaAutostart -Disable

# Gaming


# Scheduled


# Defender & Security


# Context


# Other

ControlPanelView -SmallIcons
TaskbarSearch -Hide

Refresh
Errors
```

**Screenshots**
![Screenshot 2021-02-24 085737](https://user-images.githubusercontent.com/1048928/109011054-8688c800-767e-11eb-9082-67c4bedd95fe.png)
![Screenshot 2021-02-24 085809](https://user-images.githubusercontent.com/1048928/109011056-8688c800-767e-11eb-8f83-c9d9b35f406c.png)

**Desktop (please complete the following information):**
- Windows build (19042.746): [e.g. 19042]

**Additional context**

**Comment by farag2** [comment]
Hm... I've run the script at my work place on a domain user (with admin privileges) right 15 minutes early. No errors.
Something w4ong with your current session. I really do not know what has gine wrong. May be 'll be able to look via TeamViewer tomorrow?

**Comment by bignadad** [comment]
Sure that would work for me. Thank you.

**Comment by farag2** [comment]
Hm...

**Comment by farag2** [comment]
> PinToStart -Tiles ControlPanel
> PinToStart -Tiles DevicesPrinters

The syntax is -Tiles ControlPanel, DevicesPrinters,...

You shouldn't write the command again.

**Comment by farag2** [comment]
I think the problem is this!

**Comment by farag2** [comment]
There is a bug in 5.5

> PinToStart -UnpinAll

Always unpin after pinning. So call function this first

```powershell
.\Sophia.ps1 -Functions "Pintostart -unpinall"
```
And then

```powershell
.\Sophia.ps1 -Functions "PinToStart -Tiles ControlPanel, DevicesPrinters"
```

**Comment by bignadad** [comment]
k, im testing now

**Comment by bignadad** [comment]
I just removed the pin functions all together and it didn't have any errors but there are many things that didnt work. 
search is still on taskbar
light theme didn't apply
taskview still on taskbar
ribbon not expanded in file explorer
onedrive still in tasktray
control panel not in small icons

i didn't look at everything but any idea why none of these are applying? Again I didn't get any errors and I rebooted after running it. Its the same script as i posted originally, just removed the pintostart items.

**Comment by farag2** [comment]
I need to take a look. Will you be free in 2 hours? I'm going home but currently in the Moscow underground.

**Comment by bignadad** [comment]
yes i will

**Comment by farag2** [comment]
OK. PM me on Discord: sanctuary_s#6351

**Comment by bignadad** [comment]
sent you a request on discord

**Comment by farag2** [comment]
Will be at home in 25 minutes. Wait. I need also to eat)
