### ISSUE TITLE
способы спонсирования

### ISSUE THREAD

**Issue by evgeshock** [farag2/Windows-10-Sophia-Script#140]
Вы не могли бы добавить возможность спонисирования через patreon или еще как

**Comment by farag2** [comment]
Здоров. PayPal не подходит? А какие варианты, кроме Patreon? И в чем будет преимущество?

**Comment by farag2** [comment]
<buymeacoffee.com> как?

**Comment by evgeshock** [comment]
> 
> 
> Здоров. PayPal не подходит? А какие варианты, кроме Patreon? И в чем будет преимущество
PayPal требует паспорные данные вносить - я не хочу. Да и вообще он мне вот совершенно не удобен. Сейчас час потратил, чтобы ввести новую карту - потерпел фиаско :) Любой способ, не обязательно патреон. Самое удобное это вообще с дебетовой карты деньги отправить.

**Comment by farag2** [comment]
> PayPal требует паспорные данные вносить - я не хочу. Да и вообще он мне вот совершенно не удобен. Сейчас час потратил, чтобы ввести новую карту - потерпел фиаско :) Любой способ, не обязательно патреон. Самое удобное это вообще с дебетовой карты деньги отправить.

Полностью согласен. Блин, этот buymeacoffee тоже под капотом PayPal держит, хотя кнопка якобы о дебетовой карте. А <https://opencollective.com/opencollective> подойдет? Это лишь пример доната. Надо указывать почту, куда придет ссылка на оплату.

> https://buymeacoffee.com как? - надо пробовать. Сейчас там не нашел вас
Это просто вопрос: нагуглил индуса, который побирается через него. Ну, а там, как описал выше, тоже живет PayPal. :)

**Comment by farag2** [comment]
Если хочешь, чтобы удобнее было писать мне, пингани в группе https://t.me/sophia_chat

**Comment by evgeshock** [comment]
https://buymeacoffee.com  - отлично работает. Можно с карты отправлять

**Comment by farag2** [comment]
> 
> 
> https://buymeacoffee.com - отлично работает. Можно с карты отправлять

Так там даже при выборе карты меня все равно кидает на PayPal... надо или патреоном заняться, или opencollective.

**Comment by Chilace** [comment]
https://boosty.to/boosty
от mail.ru
подписка и разовый донат
русский язык
интеграция с телеграм и дискорд

**Comment by farag2** [comment]
> https://boosty.to/boosty
> от mail.ru
> подписка и разовый донат
> русский язык
> интеграция с телеграм и дискорд

Что-то с Mail Group я не хочу контактировать. Да и для иностранцев привычнее что-то международное. В общем займусь. :godmode:

**Comment by farag2** [comment]
Открыл я этот boosty... Вот это они деньги попилили. Как это приняли вообще? Похоже, сайт даже не открывали перед сдачей.

**Comment by farag2** [comment]
https://www.donationalerts.com/r/sophiascript
Так нормально?

**Comment by farag2** [comment]
Забанили. :p Теперь так: https://yoomoney.ru/to/4100116615568835
