### ISSUE TITLE
[Feature Request] Integrate W4RH4WK's firewall telemetry and Trons Script's debloating

### ISSUE THREAD

**Issue by 3371-Alpha** [farag2/Windows-10-Sophia-Script#142]
[W4RH4WK's block-telemetry.ps1](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1) blocks the remaining data collection using the builtin firewall, since I don't believe you can completely turn off telemetry without crippling the settings. His [optimize-user-interface.ps1](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/optimize-user-interface.ps1) is also useful for decluttering the explorer sidebar but I disagree with some of the changes (like the volume bar).  [Tron Script](https://www.reddit.com/r/TronScript/) also has debloating support and other tricks. Not sure if it's redundant, but it's updated constantly and might be worth looking into.

Lastly, this part isn't a feature request but a question; do you know if registry modifications, such as turning off Nagle's Algorithm, Receive Segment Coalescing or MSCSS throttling, are useful or break more than they fix?

**Comment by farag2** [comment]
Hello! Of course I heard a lot about these projects but I dont think that it will be worth adding telemetry blocking to my script (or even upcoming GUI version). I am against blocking the telemetry. If a user wants it, I wont be in his road but we dont like when such projects absolutize telemetry blocking making more harm to OS than bringing any advantage. You cannot speed up OS by tweaking it — only tuning it for own feeling. That's the Sophia Script's message.

Keep fingers crossed for the GUI version. Some sketches: https://habr.com/ru/post/544942/#comment_22769984 ❤️
