### ISSUE TITLE
[BUG] Temp cleanup task description showing {0}

### ISSUE THREAD

**Issue by Loakii** [farag2/Windows-10-Sophia-Script#143]
![image](https://user-images.githubusercontent.com/47106497/110703756-6fa4b280-81f4-11eb-8f6c-d2a75a53da35.png)

Pretty sure this requires a path input:

https://github.com/farag2/Windows-10-Sophia-Script/blob/39df789b757af3fbeef5afeeceddb005b9ada705/Sophia/PowerShell%205.1/Sophia.psm1#L8838

Like this:
https://github.com/farag2/Windows-10-Sophia-Script/blob/39df789b757af3fbeef5afeeceddb005b9ada705/Sophia/PowerShell%205.1/Sophia.psm1#L8771

**Comment by farag2** [comment]
Yes, I've already mentioned. Fixed in 5.7.1 :)
