### ISSUE TITLE
[BUG] SoftwareDistribution cleanup never ends

### ISSUE THREAD

**Issue by Loakii** [farag2/Windows-10-Sophia-Script#144]
The wuauserv service is never being stopped so it will endlessly wait if running.
Don't think it's intended.

https://github.com/farag2/Windows-10-Sophia-Script/blob/39df789b757af3fbeef5afeeceddb005b9ada705/Sophia/PowerShell%205.1/Sophia.psm1#L8763-L8766

**Comment by farag2** [comment]
Of course no. :) Basically it's stopped.

```powershell
Name                : wuauserv
RequiredServices    : {rpcss}
CanPauseAndContinue : False
CanShutdown         : False
CanStop             : False
DisplayName         : Windows Update
DependentServices   : {}
MachineName         : .
ServiceName         : wuauserv
ServicesDependedOn  : {rpcss}
ServiceHandle       : SafeServiceHandle
Status              : Stopped
ServiceType         : Win32OwnProcess, Win32ShareProcess
StartType           : Manual
Site                :
Container           :
```

That's why the function has to wait for this status. You can check it even via `services.msc`.
