### ISSUE TITLE
Does not unpin Microsoft edge and store from taskbar

### ISSUE THREAD

**Issue by Lorindaa** [farag2/Windows-10-Sophia-Script#145]
Hello, 

I am running the latest version of the script in Win 10 2004 update but does not unpin the store and edge from the taskbar. 

Is this line correct?

# Unpin "Microsoft Edge" and "Microsoft Store" from the taskbar
# Открепить Microsoft Edge и Microsoft Store от панели задач
UnpinTaskbarEdgeStore

Thank you for your time!

**Comment by farag2** [comment]
Hello. I know about it. It's a PowerShell bug. Seems it cannot be fixed...

**Comment by farag2** [comment]
Got the point why they couldn't be unpinned...
