### ISSUE TITLE
Can I restore a backup from another computer?

### ISSUE THREAD

**Issue by Knight122** [farag2/Windows-10-Sophia-Script#148]
Hey farag2, Thanks for the script. I just ran it on a new laptop and would like to know if I can restore a backup from my other one that stopped working without breaking anything. 
I am worried the backup would install apps that the script uninstalled. 
(I’m not tech savvy, I just know more than enough to get around the computer, so forgive me if it should be obvious)

**Comment by farag2** [comment]
I got ill. I'll reply to you tomorrow...

**Comment by Knight122** [comment]
I tried it on my own and only restored the files, so there were no problems. Get well soon!

**Comment by farag2** [comment]
Write to the Telegram group. I'll reply much quicker.

**Comment by farag2** [comment]
I'm here. Can you ask this question in the Telegram group? I dont know what kind of backup you mean...
