### ISSUE TITLE
HEIF and InstallCortanaAutostart radio buttons on SSWrapper

### ISSUE THREAD

**Issue by b0tm0de** [farag2/Windows-10-Sophia-Script#152]
![sad](https://user-images.githubusercontent.com/6636688/112175712-855ca380-8c08-11eb-957e-3ec29919da71.png)

HEIF and InstallCortanaAutostart radio buttons looks like broken in SSWrapper. (Maybe forgotten semicolon?)

Sophia Script v5.8
Windows 10 / 20H2 / 19042.867

Thank you so much for this script, I love using this software, have a nice day.

**Comment by farag2** [comment]
I mentioned it too. Check these files.
[1.zip](https://github.com/farag2/Windows-10-Sophia-Script/files/6191584/1.zip)
