### ISSUE TITLE
Search of taskbar not working!!!

### ISSUE THREAD

**Issue by DrRave** [farag2/Windows-10-Sophia-Script#154]
After debloating the taskbar search bar started not working. I click on it and it doesn't do any action. 
P.S. Thanks for the fantastic tool

**Comment by farag2** [comment]
Hello. Could you provide a remote access to your PC via TeamViewer?
I don't touch wsearch service.

**Comment by DrRave** [comment]
Thnaks I've done. I restore all reg and now all works well.
Sorry for the inconvenience :)

**Comment by farag2** [comment]
NP. Cus I knew that wasn't the script failt)
