### ISSUE TITLE
Feature request: Switch from WPF to WinUI

### ISSUE THREAD

**Issue by WSLUser** [farag2/Windows-10-Sophia-Script#155]
Before submitting a bug report:

### Prerequisites

* Make sure you are able to repro it on the latest released version;
* [x ] Verify that this is not a Windows issue;
* [ ] Check the [**Before running**](https://github.com/farag2/Windows-10-Sophia-Script#fire-before-running-fire) & [**Usage**](https://github.com/farag2/Windows-10-Sophia-Script#usage) sections N/A

**Steps to reproduce**
------------------

```PowerShell

```

**Screenshots**

**Desktop (please complete the following information):**
- Windows build (**winver**): 19042

**Additional context**

I'd like to see the UI updated to use WinUI. Maybe it might be easiest to try using Project ReUnion first. WinUI is easily consumed as a nuget package and can include the pre-release version of the stable to get the dlls included if needed.

**Comment by farag2** [comment]
Hello and thank you for the interst for this project! 👍 We've been developing SophiApp, a GUI version of the script, for 1,5 years. The development is here: https://github.com/SophiaUI
The sketches you can see in the Telegram group. No ETA. May be this summer.
