### ISSUE TITLE
input prompt at  PinToStart -UnpinAll

### ISSUE THREAD

**Issue by Ranger2000** [farag2/Windows-10-Sophia-Script#158]
Hello

If I use the function "PinToStart -UnpinAll" without any Pins in Startmenu I got input prompt
![image](https://user-images.githubusercontent.com/4620349/114243507-01871300-998d-11eb-962f-64c79ac74166.png)

I use the Version: v5.10 with german localisation at 20H2

**Comment by farag2** [comment]
Hi. It's a not bug. But it's a bug in autocomplete function. The -Titles is a mandatory parameter, so it has to be assigned, but the current function "doesn't know about it". So you have to type manually (hopefully only this function) without even Sophia -Functions
PinToStart -UnpinAll

**Comment by farag2** [comment]
Ah, crap
You have to assign -Titles. It's mandatory
https://github.com/farag2/Windows-10-Sophia-Script/blob/3fba8d2051c131fdd235c22439e2156fb16a311c/Sophia/PowerShell%205.1/Sophia.psm1#L7769

I can send you an updated version tomorrow. It's 1 am now in Moscow.

**Comment by Ranger2000** [comment]
Many thanks for the fast answer, and your handsome script 😀

After I changed it to:
![image](https://user-images.githubusercontent.com/4620349/114245791-69d7f380-9991-11eb-8eda-f1eddd6632bd.png)

it worked fine 👍
![image](https://user-images.githubusercontent.com/4620349/114245836-82480e00-9991-11eb-9053-f19739065851.png)

**Comment by farag2** [comment]
And what command did you enter?

**Comment by Ranger2000** [comment]
I just changed the part in Sophia.ps1 in to following, and run the Sophia.ps1 script 😊

![image](https://user-images.githubusercontent.com/4620349/114246447-e9b28d80-9992-11eb-883f-ea4dc736b24f.png)

**Comment by farag2** [comment]
Hm... It seems we need v5.10.1. :)

**Comment by Ranger2000** [comment]
But now now. It's late 🌃
We both need to got to bed 🛌

**Comment by farag2** [comment]
No. It's time to code!

**Comment by farag2** [comment]
I've fixed in 5.10.1. The functions.ps1 was rewritten. Hopefully will upload it this evening.

**Comment by farag2** [comment]
[Sophia Script v5.10.1.zip](https://github.com/farag2/Windows-10-Sophia-Script/files/6289761/Sophia.Script.v5.10.1.zip)

**Comment by Ranger2000** [comment]
Many thanks for your'e rewriting of the function.
I just have tested the script, and now it works without the -Tiles Parameter.
The function removes all Pins and does not throw any error 👍

**Comment by farag2** [comment]
I've improved the function again. ;)
