### ISSUE TITLE
DiagnosticDataLevel

### ISSUE THREAD

**Issue by dartraiden** [farag2/Windows-10-Sophia-Script#163]
```
switch ($PSCmdlet.ParameterSetName)
	{
		"Minimal"
		{
			if (Get-WindowsEdition -Online | Where-Object -FilterScript {$_.Edition -like "Enterprise*" -or $_.Edition -eq "Education"})
			{
				# Security level
				New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 0 -Force
			}
			else
			{
				# Optional diagnostic data
				New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 1 -Force
			}
		}
		"Default"
		{
			# Required diagnostic data
			New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 3 -Force
		}
```

AllowTelemetry = 1 это ведь Required, а не Optional.
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.DataCollection::AllowTelemetry
таким образом комментарии "# Optional diagnostic data"  и "# Required diagnostic data" перепутаны местами

**Comment by farag2** [comment]
Да, есть такое :)

**Comment by Fr0stmatic** [comment]
Сперва решил, что перепутаны лишь комментарии, а скрипт работает исправно.
Но нет. Задавал DiagnosticDataLevel -Minimal, а в реестре применилось AllowTelemetry=3

**Comment by farag2** [comment]
@Fr0stmatic Нет, физически не могло 3 прописать. Ты просто опечатался.

https://github.com/farag2/Windows-10-Sophia-Script/blob/d858a6f24d39e6e98f1d16c8002b072da0d9031d/Sophia/PowerShell%205.1/Sophia.psm1#L263

**Comment by farag2** [comment]
Открою секрет: ничего плохого в 3 нет. Даже наоборот: плохо выключать телеметрию, чем включать ее. Просто людям мозги промыли говноблоггеры, не понимающие, как ОС работает, вот люди и борются с ветреными мельницами.

**Comment by farag2** [comment]
Наверное, 5.10.3 выпущу. Подправил функцию DiagnosticDataLevel.

**Comment by farag2** [comment]
То есть станет вот так

```powershell
"Minimal"
{
	if (Get-WindowsEdition -Online | Where-Object -FilterScript {$_.Edition -like "Enterprise*" -or $_.Edition -eq "Education"})
	{
		# Security level
		New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 0 -Force
	}
	else
	{
		# Required diagnostic data
		New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 1 -Force
	}
	New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name MaxTelemetryAllowed -PropertyType DWord -Value 1 -Force

	New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack -Name ShowedToastAtLevel -PropertyType DWord -Value 1 -Force
}
"Default"
{
	# Optional diagnostic data
	New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 3 -Force
	New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name MaxTelemetryAllowed -PropertyType DWord -Value 3 -Force

	New-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack -Name ShowedToastAtLevel -PropertyType DWord -Value 3 -Force
}
```

**Comment by Fr0stmatic** [comment]
Хммм... Оказывается, помимо спонтанных переключений телеметрии из ЦО в самом скрипте заложено переключение AllowTelemetry на 3, из функции RecommendedTroubleshooting (что делает бессмысленным изменение параметров функции DiagnosticDataLevel, стоящей выше)
https://github.com/farag2/Windows-10-Sophia-Script/blob/d858a6f24d39e6e98f1d16c8002b072da0d9031d/Sophia/PowerShell%205.1/Sophia.psm1#L6172

**Comment by farag2** [comment]
> (что делает бессмысленным изменение параметров функции DiagnosticDataLevel, стоящей выше)

https://github.com/farag2/Windows-10-Sophia-Script/blob/d858a6f24d39e6e98f1d16c8002b072da0d9031d/Sophia/PowerShell%205.1/Sophia.ps1#L763

Внимательно читаем то, что запускаем)

**Comment by Fr0stmatic** [comment]
Да, тут я сам сглупил. 
Вот эти смягчённо-образные Майкрософтовские описания "обязательных/необязательных диагностичских данных", означающих сборную солянку телеметрии — та ещё хитрость, которую я проморгал в настройках системы и в скрипте.
Может, стоит дополнительно указать, что означают Minimal и Default в DiagnosticDataLevel (+ в RecommendedTroubleshooting доработать примечание, дескать скрипт автоматически изменит параметр сбора данных), чтобы дурачки вроде меня не путались?

**Comment by farag2** [comment]
@Fr0stmatic, я параллельно отношусь к телеметрии и у себя ее включаю. Описание подправлю.

**Comment by farag2** [comment]
`Автоматически запускать средства устранения неполадок, а затем уведомлять
Необходимо установить уровень сбора диагностических сведений ОС на "Необязательные диагностические данные", чтобы работала данная функция
`

**Comment by dartraiden** [comment]
> Вот эти смягчённо-образные Майкрософтовские описания "обязательных/необязательных диагностичских данных"

Да, в принципе, там всё стройно (кроме того, что уровень 2 отсутствует в GUI настроек панели управления). 
3 - это необязательные данные, то, что включено по умолчанию, если во время установки Windows не трогать крыжики
2 - расширенные данные, отсутствует в GUI настроек
1 - обязательные данные, некий минимум, меньше которого в Home/Pro не опуститься
0 - только в Corp/Edu

**Comment by farag2** [comment]
Исправил все. Завтра выложу.
