### ISSUE TITLE
Ability to hide/uninstall "News and interests"

### ISSUE THREAD

**Issue by pm4rcin** [farag2/Windows-10-Sophia-Script#184]
### Prerequisites

* [x] Make sure you are able to repro it on the latest released version;
* [ ] Verify that this is not a Windows issue;
* [x] Refer to the [**Before running**](https://github.com/farag2/Windows-10-Sophia-Script#fire-before-running-fire).
* [x] Refer to the [**How to use**](https://github.com/farag2/Windows-10-Sophia-Script#how-to-use).
### Steps to reproduce
Hover right mouse button on weather/news icon to see it.

**Screenshots**
![Przechwycenie obrazu ekranu_2021-05-26_10-00-44](https://user-images.githubusercontent.com/37148802/120039845-18dd9680-bff5-11eb-952d-81badbfc511c.png)

## Environment data
```powershell
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Additional context**
I think it's probably not possible to uninstall it but I'm not sure. What I know is that you can turn it off with clicking Right mouse button on taskbar and on the "News and interests" there's option to disable that.

**Comment by farag2** [comment]
You're faster than me. I'm going to add it in the 5.10.6 release. :) The code is very simple

```powershell
#Disable
New-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds -Name ShellFeedsTaskbarViewMode -PropertyType DWord -Value 2 -Force

# Restart
```

The full function will turn the News off instantly, without restarting.
