### ISSUE TITLE
choose opposite

### ISSUE THREAD

**Issue by trinib** [farag2/Windows-10-Sophia-Script#186]
not seeing option to choose opposite

**Comment by trinib** [comment]
but i backed up ps1 file from old version , ill use that method for now .. No scratch that .. it dont import

**Comment by farag2** [comment]
Opposite where?

**Comment by trinib** [comment]
![Annotation 2021-06-04 061953](https://user-images.githubusercontent.com/18756975/120787083-fb309580-c4fc-11eb-83d5-4b3772a69cd4.jpg)

**Comment by trinib** [comment]
I can't even run this script again... when I click output, run poweshell remains blank

**Comment by farag2** [comment]
Sorry, I'm busy now. David has released a totally new Wrapper 2.0
https://github.com/farag2/Windows-10-Sophia-Script/releases/tag/5.10.6

**Comment by trinib** [comment]
> Sorry, I'm busy now. David has released a totally new Wrapper 2.0
> https://github.com/farag2/Windows-10-Sophia-Script/releases/tag/5.10.6

I got it to work.. but can you please add back option to revert or what you had before "opposite option"

**Comment by farag2** [comment]
Only he develops it. I ping him.

**Comment by farag2** [comment]
He promised to add it to the v2.0.1.
