### ISSUE TITLE
Missing in Sophia Script Wrapper 2.0

### ISSUE THREAD

**Issue by newden** [farag2/Windows-10-Sophia-Script#187]
Missing there in UI and result script:
TaskViewButton
PeopleTaskbar
SecondsInSystemClock

![image](https://user-images.githubusercontent.com/45799573/120802457-1aeeaa80-c54b-11eb-9d32-68b0f1d81b5c.png)

**Comment by farag2** [comment]
I have these functions in 21H1. In my understanding, you're using the LTSC version. It doesn't support those functions. So there is no bug. :)

**Comment by newden** [comment]
![image](https://user-images.githubusercontent.com/45799573/121017965-8c766500-c7a6-11eb-947f-0511eb5402f1.png)

**Comment by farag2** [comment]
Эх, ты. :)
