### ISSUE TITLE
Same key for both choices for the function `SetUserShellFolderLocation -Custom`

### ISSUE THREAD

**Issue by hossamdash** [farag2/Windows-10-Sophia-Script#190]
Select a folder for the "Music" folder
[S] Select  [S] Skip  [?] Help (default is "S"):
leaving it empty and pressing enter works in skipping the function, typing S causes it open the file dialog. different keys should be chosen

**Comment by farag2** [comment]
Agree. I'll fix it in 5.10.7. thanks
