### ISSUE TITLE
A Wrong Localization Name

### ISSUE THREAD

**Issue by flashercs** [farag2/Windows-10-Sophia-Script#196]
The Chinese Localization Folder Name Should be `zh-CN`, not `cn-CN`.
The command `[System.Globalization.CultureInfo]::GetCultureInfo("cn-CN")` gets a cultureinfo of `Unknown Locale (cn-CN)`;and `[System.Globalization.CultureInfo]::GetCultureInfo("zh-CN")` gets the correct cultureinfo of `Chinese (Simplified, PRC)`.

**Comment by farag2** [comment]
Nice. I didn't know)

**Comment by farag2** [comment]
What about the translation quality? May be you can inprove it?

**Comment by flashercs** [comment]
You do a good job. The translation is very good, I just modified a few words to make it more accurate. I have created a pull request.
