### ISSUE TITLE
Windows Color settings

### ISSUE THREAD

**Issue by Asxetos21** [farag2/Windows-10-Sophia-Script#199]
I do not like windows dark colors, but it seems editing Sophia.ps1 settings "WindowsColorScheme" and "AppMode" to light isn't enough.
I end up with a messed up taskbar with black text in the system area (note, i use "StartIsBack"). In general the hole "personalisation" settings get a little messed up.

What else needs to be edited to stop this?

Thanks

**Comment by farag2** [comment]
Couldn't reproduce. Works as it should: I switch from dark to light, and vice versa instantly, without any pixel artifacts on my personal Surface Laptop 3.
May be it causes for you because of StartIsBack.

**Comment by Asxetos21** [comment]
Thanks for the answer, 
It's not any kind of artifacts.

I use the light color theme, so the text and icon color on the right side are white (the clock text, network icon, language icon battery etc).

After the script is done (with the 2 settings edited), i end up with the same color theme all over windows, except the taskbar icon and text color which turn black. Every time i apply the script.

I found out how to change them back to white, but it's quite tricky.

PS, GREAT script, the taskbar color glitch i experience is really minor.

**Comment by farag2** [comment]
It works even in my VM. :)

**Comment by farag2** [comment]
Hopefully, the v5.10.8 will be released tomorrow with Wrapper 2.0.2. 😸
