### ISSUE TITLE
TaskbarSearch -SearchIcon is not working

### ISSUE THREAD

**Issue by Hxppdv** [farag2/Windows-10-Sophia-Script#200]
I noticed that the script did not change my TaskbarSearch, which I later found out was because the script did not successfully modify the registry.
Strangely both Hide and SearchBox parameters work fine.

Then I checked sophia.psm1 and saw
`		[Parameter(
			Mandatory = $true,
			ParameterSetName = "ShowIcon"
		)]
		[switch]
		$SearchIcon,`
I tried to change it to
`		[Parameter(
			Mandatory = $true,
			ParameterSetName = "SearchIcon"
		)]
		[switch]
		$SearchIcon,`
Then everything works fine, but I don't know if it's just a spelling mistake.

**Comment by farag2** [comment]
You're god damn right.
