### ISSUE TITLE
suggestion - actions aproval.

### ISSUE THREAD

**Issue by TristisOris** [farag2/Windows-10-Sophia-Script#208]
this appear in last win21H1 build.
any file moving and other actions, required aproval, even under admin account with disabled UAC.
do you know any solution for this?

**Screenshots**
![изображение](https://user-images.githubusercontent.com/1270117/124030523-ef05fe00-d9fe-11eb-9395-4fd8ffd6ca6e.png)

**Comment by farag2** [comment]
Hi. To disable UAC. I don't provide a feature for this in the script, and don't advice to do it.

<https://www.tenforums.com/tutorials/112488-enable-disable-user-account-control-uac-windows.html>
