### ISSUE TITLE
Disable tooltip timeout in Wrapper.exe

### ISSUE THREAD

**Issue by nitin2953** [farag2/Windows-10-Sophia-Script#214]
@BenchTweakGaming 
Disable Tooltip timeout in wrapper.exe, I need more time to read those

**Comment by farag2** [comment]
I've already reported it to him. Fiized in 2.2. I'll attach the new version here for you.

**Comment by BenchTweakGaming** [comment]
[SSW V2 July 23 2021.zip](https://github.com/farag2/Windows-10-Sophia-Script/files/6869049/SSW.V2.July.23.2021.zip)
