### ISSUE TITLE
Making the script more user-friendly: Encapsulation and separation of concerns

### ISSUE THREAD

**Issue by skycommand** [farag2/Windows-10-Sophia-Script#55]
Hello. 😊

This script currently packs 150+ functions; anyone willing to apply only a subset of them needs to open the script and comment out the relevant section. The problem is, this person must know enough PowerShell to be able to distinguish sections in the first place. If they miss commenting out the closing `}`, the result could be quite unexpected.

One of the principles of writing good code is: Use functions to avoid code repetition.

## Technique 1

Currently, there are a lot of sections in the script that look like this:

```PowerShell
if (-not (Test-Path $SomeRegistryPath))
{
	New-Item -Path $SomeRegistryPath -Force
}
New-ItemProperty -Path $Path -Name $Name -PropertyType DWord -Value $Value -Force
```

...or simply, this:

```PowerShell
New-ItemProperty -Path $Path -Name $Name -PropertyType DWord -Value $Value -Force
```

It can be encapsulated into a function, like this:
```PowerShell
function Set-RegistryDword {
  [CmdletBinding()]
  param (
    [String]$Path,
    [string]$Name,
    [Int64]$Value
  )

  if (-not (Test-Path $Path))
  {
    New-Item -Path $Path -Force
  }
  New-ItemProperty -Path $Path -Name $Name -PropertyType DWord -Value $Value -Force
}
```

You can use this function to encapsulate the data and logic separately. Here is how [lines 343 through 395](https://github.com/farag2/Windows-10-Setup-Script/blob/b2e1c9a16913cb515aa376e68e16b56e3d117a5e/Win%2010%202004.ps1#L343-L395) would look like:

```PowerShell
function Set-RegistryDword {
  [CmdletBinding()]
  param (
    [String]$Path,
    [string]$Name,
    [Int64]$Value
  )

  if (-not (Test-Path $Path))
  {
    New-Item -Path $Path -Force
  }
  New-ItemProperty -Path $Path -Name $Name -PropertyType DWord -Value $Value -Force
}

$SettingsToSet = @(
  # Do not suggest ways I can finish setting up my device to get the most out of Windows
  # Не предлагать способы завершения настройки устройства для максимально эффективного использования Windows
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement','ScoobeSystemSettingEnabled',0),

  # Do not offer tailored experiences based on the diagnostic data setting
  # Не предлагать персонализированные возможности, основанные на выбранном параметре диагностических данных
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy','TailoredExperiencesWithDiagnosticDataEnabled',0),

  # Show "This PC" on Desktop
  # Отобразить "Этот компьютер" на рабочем столе
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel','"{20D04FE0-3AEA-1069-A2D8-08002B30309D}"',0),

  # Do not use check boxes to select items
  # Не использовать флажки для выбора элементов
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','AutoCheckSelect',0),

  # Show hidden files, folders, and drives
  # Показывать скрытые файлы, папки и диски
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','Hidden',1),

  # Show file name extensions
  # Показывать расширения для зарегистрированных типов файлов
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','HideFileExt',0),

  # Do not hide folder merge conflicts
  # Не скрывать конфликт слияния папок
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','HideMergeConflicts',0),

  # Open File Explorer to: "This PC"
  # Открывать проводник для: "Этот компьютер"
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','LaunchTo',1),

  # Do not show all folders in the navigation pane
  # Не отображать все папки в области навигации
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','NavPaneShowAllFolders',0),

  # Do not show Cortana button on taskbar
  # Не показывать кнопку Кортаны на панели задач
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','ShowCortanaButton',0),

  # Do not show sync provider notification within File Explorer
  # Не показывать уведомления поставщика синхронизации в проводнике
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','ShowSyncProviderNotifications',0),

  # Do not show Task View button on taskbar
  # Не показывать кнопку Просмотра задач
  ('HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced','ShowTaskViewButton',0)
)

if ($SettingsToSet.Count -ne 0) {
  foreach ($item in $SettingsToSet) {
    Set-RegistryDword -Path $item[0] -Name $item[1] -Value $item[2]
  }
}
```

Two things have happened:

1. Commenting out the undesired settings has become much easier for the laymen, as they don't see the technical `New-ItemProperty` part.
2. Who says they have to edit the script? You can put the settings into a separate .xml file. The user simply edits that file instead of editing the script. That way, if one day, you decided to port your code to C#, Python, or Node.js, well, you can just port the logic.

There caveats though:

1. Some parts of the script aren't as easy to encapsulate.
2. Some objectives can only be accomplished by setting two or more Registry values at once, or by running other commands, like `dism` or `taskman`. Here's when Technique 2 helps.

## Technique 2

It possible to break this script into two files: `Win 10 2004 Main.ps1` and `Win 10 2004 Logic.psm1`.

`Win 10 2004 Logic.psd1` would look like this:

```PowerShell
# Set the minimal operating system diagnostic data level
# Установить минимальный уровень отправляемых диагностических сведений
function Set-OsDiagLevelFarag {
  if ((Get-WindowsEdition -Online).Edition -eq "Enterprise" -or (Get-WindowsEdition -Online).Edition -eq "Education")
  {
    # "Security"
    # "Безопасность"
    New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 0 -Force
  }  
  else
  {
    # "Basic"
    # "Базовый"
    New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection -Name AllowTelemetry -PropertyType DWord -Value 1 -Force
  }   
}  

# Turn off Windows Error Reporting
# Отключить отчеты об ошибках Windows
function Disable-WindowsErrorReportingFarag {
  New-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\Windows Error Reporting" -Name Disabled -PropertyType DWord -Value 1 -Force
}

# 
# ...
# ...
# ...
# 
```
As you can see, this sample code is just the lines [219 through 236](https://github.com/farag2/Windows-10-Setup-Script/blob/b2e1c9a16913cb515aa376e68e16b56e3d117a5e/Win%2010%202004.ps1#L219-L236) of the script. The only change here is the addition of `function {}` definition.

Now, the  `Win 10 2004 Main.ps1` could look like this:

```PowerShell
Import-Module `Win 10 2004 Logic.psm1` -Scope Local # Maybe "Local" isn't appropriate. Let's check PowerShell help later.

Set-OsDiagLevelFarag 
Disable-WindowsErrorReportingFarag
# 
# ...
# ...
# ...
# 
```

This script just calls functions inside `Win 10 2004 Logic.psm1`. Disabling the functions that the user doesn't need is a matter of commenting only one line.

But there is something even better: People can import `Win 10 2004 Logic.psm1` and just run one or two of its functions.

## Which technique to use? 1 or 2?

Both. Technique 1 is useful for `Win 10 2004 Logic.psm1`.

However, both techniques need refining. I bet that if I familiarize myself with the script, I can make better suggestions. I haven't studied the script thoroughly, [since I was introduced to it](https://www.neowin.net/news/this-windows-10-setup-script-lets-you-fine-tune-around-150-functions-for-new-installs#comment-598576071). I have a life of my own, too, you know.

**Comment by farag2** [comment]
Done)
