### ISSUE TITLE
Making the script more user-friendly: Those cryptic app names

### ISSUE THREAD

**Issue by skycommand** [farag2/Windows-10-Sophia-Script#56]
Hello. 😊

Please take a look at this screenshot:
![Image](https://i.imgur.com/stEsBkN.png)

- Does an ordinary user know what Microsoft.549981C3F5F10 is? What about you? (It's Cortana, by the way.)
- How about c5e2524a-ea46-4f67-841f-6a9465d9d515? (It is File Explorer.)
- Or Microsoft.MSPaint. (It is NOT Microsoft Paint. It is Paint 3D.)

I recommend the user should know the friendly name of these apps. 

You can find a script called [Inventory AppX Packages.ps1](https://github.com/skycommand/Admin-scripts/blob/master/AppX/Inventory%20AppX%20Packages.ps1) on my repo. It helps you discover the friendly names.

**Comment by farag2** [comment]
@skycommand DMed you on MDL yesterday.

**Comment by sinichi19** [comment]
and if its ok to by default already checked the Uninstall all users

**Comment by farag2** [comment]
Don't think i'd be nice idea. If someone decide to restore packages he'll realise that it's possible only by searching for appx packages.

**Comment by skycommand** [comment]
I agree. It's not okay. From my experience, people want to check this box only as a way of demonstrating their extent of dislike for a certain app or Microsoft. It is a psychological thing, not a functional one.

In reality, most computers are single-user and this checkbox serves no purpose anyway. On multi-user computers, like mine, I have brothers and sisters who have their own choices, for varying reasons.

**Comment by farag2** [comment]
Done with way much more easier

```powershell
$Packages = [Windows.Management.Deployment.PackageManager,Windows.Web,ContentType=WindowsRuntime]::new().FindPackages()
$Packages | Select-Object -ExpandProperty Id -Property DisplayName | Format-Table -Property Name, DisplayName
```
