### ISSUE TITLE
It deleteS your WSL install 

### ISSUE THREAD

**Issue by asolopovas** [farag2/Windows-10-Sophia-Script#65]
If you skip installation of WSL all your existing wsl file are wiped immediately.

**Comment by farag2** [comment]
Build? Script version...

**Comment by asolopovas** [comment]
version. 18.08.2020, wiver: ![image](https://user-images.githubusercontent.com/6893216/93895224-80657880-fce7-11ea-8fc0-c1ee8a825caf.png)

**Comment by farag2** [comment]
Why do you use the outdated script version? I'll check the code tomorrow.

**Comment by asolopovas** [comment]
I did not think that the default install of the script would kill my wsl installation that had files on it, but what can you do?

**Comment by farag2** [comment]
How it can be uninstalled? You mean it disabled WSL feature or what?

**Comment by asolopovas** [comment]
I have pressed enter at the point when script asked me to install wsl I think default was skip, the next thing I know that my existing wsl installation is gone with all the files, meaning I had to go and download ubuntu again.

**Comment by farag2** [comment]
@asolopovas It's very strange, 'cos

https://github.com/farag2/Windows-10-Sophia-Script/blob/9ea49ee73decd842eea139b4ed6272f3baa8d12a/200x/2004.ps1#L993

the default choice is of course "skip". I looked through the all WSL related sections but couldn't find any code that can cause WSL uninstalling. Was your .wslconfig deleted?

```powershell
$env:USERPROFILE\.wslconfig
```

or

```powershell
$env:HOMEPATH\.wslconfig
```

**Comment by asolopovas** [comment]
I am not sure if .wslconfig  got deleted as I had to work and installed ubuntu from scratch so there is no way I can reconcile that. I noticed missing installation after the script complete. I am sure you had not intention do delete anything I have ran your script previously and never had this issue at hand. 
Strangely enough while the script was running I was on the phone and did not do anything else at that moment which could cause the wsl installation to vanish.

**Comment by asolopovas** [comment]
I will try test run it on my other machine and check if that happens again.

**Comment by farag2** [comment]
Hm... So the sequence of actions is as follows: install WSL, intall Ubuntu and the run the script? I can do some tests tomorrow.

**Comment by asolopovas** [comment]
Yes that what I did.
