### ISSUE TITLE
How to revert the changes ?

### ISSUE THREAD

**Issue by aruntemme** [farag2/Windows-10-Sophia-Script#66]
Actually I debloated my windows with this script, now I want to revert it back for some reasons.
How can I do that?

**Comment by farag2** [comment]
Hello. Please fill in the issue template to give more info about your OS and the script version.

**Comment by farag2** [comment]
Anyway you can do it with the 5.0 version: https://github.com/farag2/Windows-10-Sophia-Script/releases/tag/5.0-rc5
Comment functions in Preset.ps1 that you do not want to be ran and comment out that you want to be ran. Every function has a description.

**Comment by aruntemme** [comment]
Thank you for the answer and yes I reverted the changes

**Comment by farag2** [comment]
You're welcome. Do not forget to report any bug! I'll upload 5.0.1 soon. Just cosmetic changes. Nothing fixed or new )
