### ISSUE TITLE
Outlook 365 hangs

### ISSUE THREAD

**Issue by einnairo** [farag2/Windows-10-Sophia-Script#67]
Hi Does anyone face the same problem as me. Windows 10 Pro 64bit Version 2004.

After doing this, outlook 365 hangs frequently. Meaning it freezes and shows (Not Responding). 
I have to restart the program.

I have tried to modify office in settings meaning repair only. Did not do a full uninstall and reinstall as
I dont want to mess with my emails. 

By frequently crashing, I mean at least 3 times a day. 

 Any ideas?

**Comment by farag2** [comment]
Hello. I'm using Office 365. I do not belive that enabling/disabling some Win features can cause Outlook freezes. I'll try to find trial Office 365 and make some tests.

**Comment by farag2** [comment]
Installed Outlook 365. So did you install it first and then applied script or vise versa?

**Comment by farag2** [comment]
As a last resort I can connect to your PC via TeamViewer to see the bug by myself...

**Comment by farag2** [comment]
Couldn't reproduced. :( Everything runs very smoothly.

**Comment by einnairo** [comment]
Hi Farag,Nevermind then. If I cannot take it later I may reinstall the whole office. I had my outlook 365 before running your script. 
Keep up the good work! 
cheers 


    On Friday, September 25, 2020, 03:06:46 PM GMT+8, Dmitry Nefedov <notifications@github.com> wrote:  
 
 


Couldn't reproduced. :( Everything runs very smoothly.
