### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jimkal906** [farag2/Windows-10-Sophia-Script#68]
Whats the difference between 24.09.2020 and 18.08.2020 bc you dont have any description about any improvements or bugs. which version we must download? The option Removed the "Show the "File Explorer" and "Settings" folders on Start" section; it was a cool feature for me . can we enable it? first time asking on github :(

**Comment by farag2** [comment]
The main differences are that every tweak was rewritten into function. No bugs fixed, but code was improved. So I adviced to use the 5.0 version if you apply it to the 2004 version.

You can create a function with the code from older version and add its' name into preset file.

**Comment by jimkal906** [comment]
![11](https://user-images.githubusercontent.com/71830530/94169303-53f05e80-fe97-11ea-8f18-a700c8b11d11.png)
i must put only the first paragraph or all ? i took it from 17.06.2020

**Comment by farag2** [comment]
Paste this function in Sophia.psm1

```powershell
function ShowStartFolders
{
	# Show the "File Explorer" and "Settings" folders on Start
	# Отобразить папки "Проводник" и "Параметры" в меню "Пуск"
	# https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/199
	$Folders = @("File Explorer", "Settings")
	$StartMenu = Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount\*windows.data.unifiedtile.startglobalproperties\Current"
	$Data = $StartMenu.Data[0..19] -join ","
	$Data += ",203,50,10,$($Folders.Length)"

	# File Explorer
	$Data += ",5,188,201,168,164,1,36,140,172,3,68,137,133,1,102,160,129,186,203,189,215,168,164,130,1,0"

	# Settings
	$Data += ",5,134,145,204,147,5,36,170,163,1,68,195,132,1,102,159,247,157,177,135,203,209,172,212,1,0"
	$Data += ",194,60,1,194,70,1,197,90,1,0"

	New-ItemProperty -Path $StartMenu.PSPath -Name Data -PropertyType Binary -Value $Data.Split(",") -Force

	# Restart the Start menu
	Stop-Process -Name StartMenuExperienceHost -Force -ErrorAction Ignore
}
```

and add this function name in Preset.ps1

```
ShowStartFolders
```

That's it!
