### ISSUE TITLE
Please make it work on Powershell7

### ISSUE THREAD

**Issue by Ranger2000** [farag2/Windows-10-Sophia-Script#70]
I used the release from 25.09.2020 with an Windows 10 version 2004.
With Powershell 5.1 it does worked fine, but with Powershell 7.0 it got some errors.

<img width="601" alt="Screenshot_1" src="https://user-images.githubusercontent.com/4620349/94315991-dbb39700-ff83-11ea-84e4-6097d7bfc33f.png">
<img width="708" alt="Screenshot_2" src="https://user-images.githubusercontent.com/4620349/94316000-deae8780-ff83-11ea-9b9b-706a9b57963a.png">

**Comment by farag2** [comment]
Hello. I know it. Not all cmdlets are supported by PS 7. But when a PS 7.7 will be shipped within Windows 10 I'll start a migration to it. So now it couldn't be ran within it.
https://github.com/PowerShell/PowerShell/issues/11732

**Comment by farag2** [comment]
I start experimenting with

```powershell
Import-Module -Name Microsoft.PowerShell.Management -UseWindowsPowerShell -Force
```
May soon the script will be compatible with PS 7.2...
