### ISSUE TITLE
Cant Open Shared Folder or Printer

### ISSUE THREAD

**Issue by sinichi19** [farag2/Windows-10-Sophia-Script#71]
Good Day,

To All,

First nice work for the script and thank you very much.

After I run the Sophia-Script 5.0.1 cant open shared folder.
Requesting for your kind assistance if there is need to edit to the script or I need to adjust to the windows.

**Expected Behavior:**
After run the script remove all unnecessary apps or bloatware windows can shared folder or access by other computer. (private sharing only)

**Actual Behavior** 
Removed all bloatware but cant access the shared folder and printer.

Thank You and More Power

**Comment by sinichi19** [comment]
"Workaround"
Re-add new inbound Firewall rules

Predefined - File and Printer Sharing (SMB-In) then allow the connection restart na computer and the File and Printer sharing is now accessible

**Comment by farag2** [comment]
Hello! So you enabled SMB1 and it worked? When I read it 2 hours ago I thought
https://github.com/farag2/Windows-10-Sophia-Script/blob/4dec50be79a17b3ecee3b32e987850453ab72aca/Sophia/Sophia.psm1#L3620
is the the cause.

**Comment by sinichi19** [comment]
> Hello! So you enabled SMB1 and it worked? When I read it 2 hours ago I thought
> https://github.com/farag2/Windows-10-Sophia-Script/blob/4dec50be79a17b3ecee3b32e987850453ab72aca/Sophia/Sophia.psm1#L3620
> 
> 
> is the the cause.

No sir not the SMB1, after I this rule
![image](https://user-images.githubusercontent.com/44279612/94775316-2bfe7f00-03f2-11eb-99f3-d64d80344683.png)

**Comment by farag2** [comment]
Is this ruled enabled by default (I can check but later)? I mean did the script disabled it?

**Comment by sinichi19** [comment]
> Is this ruled enabled by default (I can check but later)? I mean did the script disabled it?

Yes sir its enable by default but after i run the script cant access the shared folder but after I re add the same rules its works

**Comment by farag2** [comment]
I will check it on the VM. Are your PCs in an AD? Cos mine are.

**Comment by sinichi19** [comment]
> I will check it on the VM. Are your PCs in an AD? Cos mine are.

No sir only personal computer or standard setup and only need to share my folder and printer

**Comment by farag2** [comment]
Is "Work Folders Client" needs to be enabled?

**Comment by sinichi19** [comment]
sorry not expert to that,  I need to run that command after i run the script?

**Comment by farag2** [comment]
No. It indicates the state of the "WorkFolders-Client" feature: enabled or disabled. Run it and send the output. Just for a test purpose.

**Comment by sinichi19** [comment]
> No. It indicates the state of the "WorkFolders-Client" feature: enabled or disabled. Run it and send the output. Just for a test purpose.

oh sorry ok i will try, but i think tommorow will send the output after work 

thank you for your kind assistance, God bless and keep safe

**Comment by farag2** [comment]
Just got back to your problem )

**Comment by farag2** [comment]
How did you get that window? on your screenshot? I haven't got such a rule list.

**Comment by farag2** [comment]
Yeah, I have to test at home, cos' I'm able to ping in my network even on a VM without "File and Printers Sharing" enabled.

**Comment by sinichi19** [comment]
> Yeah, I have to test at home, cos' I'm able to ping PCs in my network even on a VM without "File and Printers Sharing" enabled.

(Get-WindowsOptionalFeature -Online -FeatureName "WorkFolders-Client").State
**Disabled**

that's the result sir after I run the script and the command you mention.

-------

**Comment by farag2** [comment]
Yep. Tested at home. I need to Google )

**Comment by sinichi19** [comment]
> Yep. Tested at home. I need to Google )

thank you sir, more power and god bless

**Comment by farag2** [comment]
```powershell
$FirewallRules = @(
	# File and printer sharing
	"@FirewallAPI.dll,-32752",

	# Network discovery
	"@FirewallAPI.dll,-28502"
)
Set-NetFirewallRule -Group $FirewallRules -Profile Private -Enabled True
Set-NetFirewallRule -Profile Public, Private -Name FPS-SMB-In-TCP -Enabled True
Set-NetConnectionProfile -NetworkCategory Private
```

Think I've fixed it.

**Comment by sinichi19** [comment]
> ```powershell
> $FirewallRules = @(
> 	# File and printer sharing
> 	"@FirewallAPI.dll,-32752",
> 
> 	# Network discovery
> 	"@FirewallAPI.dll,-28502"
> )
> Set-NetFirewallRule -Group $FirewallRules -Profile Private -Enabled True
> Set-NetFirewallRule -Profile Public, Private -Name FPS-SMB-In-TCP -Enabled True
> Set-NetConnectionProfile -NetworkCategory Private
> ```
> 
> Think I've fixed it.

Nice, I will try this today , Thank you Sir

**Comment by sinichi19** [comment]
> > ```powershell
> > $FirewallRules = @(
> > 	# File and printer sharing
> > 	"@FirewallAPI.dll,-32752",
> > 
> > 	# Network discovery
> > 	"@FirewallAPI.dll,-28502"
> > )
> > Set-NetFirewallRule -Group $FirewallRules -Profile Private -Enabled True
> > Set-NetFirewallRule -Profile Public, Private -Name FPS-SMB-In-TCP -Enabled True
> > Set-NetConnectionProfile -NetworkCategory Private
> > ```
> > 
> > 
> > Think I've fixed it.
> 
> Nice, I will try this today , Thank you Sir

Sir @farag2 already tested and can now access the shared folder also can ping the computer after added to the script (Set-NetFirewallRule -Profile Public, Private -Name FPS-SMB-In-TCP -Enabled True)

Thank You and More Power
