### ISSUE TITLE
Function DisableTailoredExperiences defined twice

### ISSUE THREAD

**Issue by crumbl3d** [farag2/Windows-10-Sophia-Script#72]
Script version: 5.0.1.

While looking through the preset file I noticed that there is a line `DisableTailoredExperiences` and instead of having
`# EnableTailoredExperiences` after it, there is `# DisableTailoredExpereriences`. Then I looked into the Sophia.psm1 file and lo and behold there are two function definitions for `DisableTailoredExperiences`. I don't have time at the moment but I can add a pull request later to fix this issue.

**Comment by farag2** [comment]
LOL. Yes, my mistake. The file are getting bigger day by day. Thanks. I'll release a new version in some days with all small fixes.

**Comment by crumbl3d** [comment]
Also, DisableSuggestedContent is defined twice... I suggest naming the second one DisableSuggestedSetup. Same for EnableSuggestedContent.
