### ISSUE TITLE
Question about LTSC

### ISSUE THREAD

**Issue by mikhoul** [farag2/Windows-10-Sophia-Script#77]
Are you going to update the LTSC version to version 5.x so that it is easier to use?  🤔

Thanks for your work 👍

**Comment by farag2** [comment]
Hello. Think I going to do it on Monday (without any release page) or with the 5.2 release.

**Comment by mikhoul** [comment]
Thanks a lot for the quick answer !

**Comment by farag2** [comment]
I always make a quick rrply when in the Moscow undeground))

**Comment by mikhoul** [comment]
@farag2   Do you have some news about the LTSC version ? 

Regards :octocat:

**Comment by farag2** [comment]
Have not free time. Only after October 28.

**Comment by methanoid** [comment]
Please clarify - is LTSC ONLY supported in 5.0 script and none of scripts since then work with LTSC?
