### ISSUE TITLE
[VirtualBOx] Install Linux (Ubuntu) new Virtual Machine 

### ISSUE THREAD

**Issue by sinichi19** [farag2/Windows-10-Sophia-Script#81]
Before submitting a bug report:

### Prerequisites

* Make sure you are able to repro it on the latest released version;
* [X ] Verify that this is not a Windows issue;
* [ X] Check the [**Before running**](https://github.com/farag2/Windows-10-Sophia-Script#%EF%B8%8F-before-running-%EF%B8%8F) & [**Usage**](https://github.com/farag2/Windows-10-Sophia-Script#usage) sections
Version: Sophia  5.1.1

**Problem**
Cant install Linux (ubuntu) on VirtualBox

**Steps to reproduce**

Install VirtualBox w/ extension pack
Create Virtal Machine for Linux Ubuntu Desktop 64bit
Install Linux Ubuntu 18.4.5

------------------

**Error**
![image](https://user-images.githubusercontent.com/44279612/96328967-3029ce00-107b-11eb-9cdd-826478ccdc72.png)

---------------
**Note**
Tried to install to the new Windows profile not run the Sophia Script everything works fine

**Comment by farag2** [comment]
I'll make some tests on monday...

**Comment by farag2** [comment]
I cannot reproduce the issue. How do you install Ubunti, within CD? Because the error says that the cause due to a faulty CD/DVD.

**Comment by sinichi19** [comment]
> I cannot reproduce the issue. How do you install Ubuntu, within CD? Because the error says that the cause due to a faulty CD/DVD.

Using .ISO (ubuntu)

Already installed the virtualBox when I run the script then create new virtual machine in virtual box for Ubuntu desktop
When I saw the error I downloaded new .iso of ubuntu but same error prompt 
Tried to reinstalled the VirtualBox but still encountered the same problem.

Then I tried to install the virtualbox to the computer not run the script and used the same .iso of ubuntu everything works fine

**Comment by farag2** [comment]
I see... But I didn't face that issue. Also I do recommend to use Hyper-V if your Windows 10 Edition is not SL/Core. VirtualBox absolutely sucks.

**Comment by sinichi19** [comment]
> I see... But I didn't face that issue. Also I do recommend to use Hyper-V if your Windows 10 Edition is not SL/Core. VirtualBox absolutely sucks.

awts T_T hehe,
My version of my windows is 2004 pro 64bit.

-----

Question I think there is something in the script for security dont know hehe.
If I only want to the script is to remove the unnecessary or unused apps like, oneDrive,People, weather.. etc.
and not touch the other settings of the windows. 

What I need to retain to the script? if its ok to you.

Thank You

**Comment by farag2** [comment]
Just read the preset file and comment out those functions you do not want to be ran! Well, ran only functions from ```Privacy & Telemetry```, ```OneDrive```, and ```UWP apps``` regions.
