### ISSUE TITLE
Непонятное трактование пункта настроек

### ISSUE THREAD

**Issue by paratroop3r** [farag2/Windows-10-Sophia-Script#84]
Пункт настроек включения/отключения ограничения длины пути в 256 символов. В тексте идёт подпись "Отключить", а настройка называется "Enable...". И наоборот. В итоге не понятно, что реально отработается. Даже не так. Не понятно, что именно я включаю: ограничение или разрешение длины > 256 символов.

**Comment by farag2** [comment]
Ну, а что непонятно? ```Включить ограничение Windows на 260 символов в пути``` включает ограничение, а ```Отключить ограничение Windows на 260 символов в пути``` выключает ограничение. Как по-другому можно написать?

**Comment by paratroop3r** [comment]
Смотри, что у тебя написано:

> **Enable** Windows 260 character path **limit**
> **Включить** **ограничение** Windows на 260 символов в пути
> **Enable**Win32**LongPaths**


Чувствуешь разницу? Описание говорит, что длинные пути будут запрещены. А текст команды говорит, что будут разрешены. Т.е. команда должна говорить 

> EnableWin32LongPath**Limits**

Или 

> **Disable**Win32LongPath

**Comment by farag2** [comment]
https://www.youtube.com/watch?v=4laH4zZgYvA 👍
