### ISSUE TITLE
Default значение для настроек

### ISSUE THREAD

**Issue by paratroop3r** [farag2/Windows-10-Sophia-Script#85]
Есть много "внутренних" настроек windows, которые не видны для пользователя. То есть нельзя зайти в меню того же проводника и посмотреть, а как настроено по умолчанию. Хотелось бы в скрипте видеть подпись "default" для понимания, как это заложено изначально производителем. Дело в том, что скрипт идёт преднастроенным. А поэтому во многих случаях не ясно, Вы решили настройку переписать или оставить штатной.
Другой вариант (мне кажется, более правильный), весь скрипт перевести в режим "по умолчанию". То есть так, как это настроено в системе до изменений. А дальше пользователь уже сам решит, как повлиять на ту или иную настройку.

**Comment by farag2** [comment]
То есть предлагаешь, во-первых, полностью вынести в отдельный файл "отката", а, во-вторых, четко указывать на какое значение менятеся (дефолтное или нет)?

**Comment by paratroop3r** [comment]
Нет. Оставить весь файл пресета, как есть. Но все настройки сделать дефолтными, т.е. такими, какие идут после установки винды. А дальше, опираясь на описание, пользователь сам что-то включит, что-то отключит. Другой вариант, оставить уже преднастроенный вариант, как сейчас. Но в описании к каждой настройке добавить слово Default, если она является штатной из коробки.

**Comment by farag2** [comment]
Тогда легче вообще закомментировать все. Смысла пресет-файла? Описание дополню. Остальное оставлю, как есть.
