### ISSUE TITLE
script doesnt seem to complete

### ISSUE THREAD

**Issue by btsambo** [farag2/Windows-10-Sophia-Script#89]
Hi, hope you're well. i'm just running the script now, have used before on another machine and works great but on this build it seems to hang after the second 'display dialogue box'

i re ran it and it seems to happen again - has the script actually completed?
![IMG_20201111_192921](https://user-images.githubusercontent.com/61805879/98856502-88bf7180-2455-11eb-98a7-49812022df87.jpg)
, i seem to remember when i ran it a month or so ago there were other things it carried on doing before completion

last system i ran it on was win 10 pro 2004 - this new pc is on 20h2 same win version

thanks

sam

**Comment by farag2** [comment]
Hi! yep, it ofc completed). It's a PowerShell fault. Even me sometimes face such issue. The only way to fix it is to restart a PC. I didn't find another one. Also try to press space. Seems console is being overbuffered and is unable to dispaly all text. PS isn't designed to develop such huge stuff. 🗡️ 
If nothing help I can see what is going wrong via may be Discord like I helped @HighPriest today.

**Comment by btsambo** [comment]
Hi, thanks for the super quick reply. hope this helps you out - i just tried another run of the script and where the second box popped up, i'd been selecting 'uninstall for all users' - this time i left it deselected and  the rest of the powershell script messages ran as per the norm - i'll re run now just to be sure and let you know the outcome

**Comment by farag2** [comment]
OK. Waiting. Anyway I can take a look at console tomorrow, if nothing helps.

**Comment by btsambo** [comment]
ok, just reran the script twice, first time selecting uninstall for all user on the second popup upon which the script seemed to hang then reran without selecting all users and the script said nothing to change and ran to completion (so must have worked like you said) - will close the query now. thanks very much for your help

**Comment by farag2** [comment]
You're welcome! :D
