### ISSUE TITLE
CommandNotFoundException with DeliveryOptimization -Disable

### ISSUE THREAD

**Issue by milahu** [farag2/Windows-10-Sophia-Script#91]
the command `Delete-DeliveryOptimizationCache` is called in `Sophia.psm1` but is never defined

```
+             Delete-DeliveryOptimizationCache -Force
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Delete-DeliveryOptimizationCache:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by farag2** [comment]
Your winver?
If I type ```Delete-DeliveryOptimizationCache```

```
Are you sure you want to delete files in Delivery Optimization Cache? You cannot undo this action.
Enter [Y] to proceed, any other key to cancel.
```

**Comment by milahu** [comment]
> Your winver?

version 1809, release date 2018-10-02 (i know, its old ....)

but the error should not be fatal ..
the script should continue and maybe show an error summary at the end

**Comment by farag2** [comment]
What the sxript verison are you running? The 5.x version supports only 2004/2009. Please read this: https://github.com/farag2/Windows-10-Sophia-Script#supported-windows-10-versions
Also 4.x version is outdated and deprecated.

**Comment by farag2** [comment]
The script shows the error summary at the end, but it seems you are running very old 10. It's time to upgrade, Luke!

**Comment by milahu** [comment]
> What the sxript verison are you running?

Version: v5.2

> Please read this

"version 1809, editions Enterprise, script 4.5"

> 4.x version is outdated and deprecated

> It's time to upgrade, Luke!

afraid so : /

suggestion: check windows version in script, require minimum version

closing as out-of-scope

**Comment by farag2** [comment]
May yes, you're right. But there are all instructions on the main page. :)
