### ISSUE TITLE
refactor: make script shorter

### ISSUE THREAD

**Issue by milahu** [farag2/Windows-10-Sophia-Script#92]
the main script `Sophia.ps1` is unnecessarily verbose

```
# Disable the "Connected User Experiences and Telemetry" service
# Отключить службу "Функциональные возможности для подключенных пользователей и телеметрия"
TelemetryService -Disable

# Enable the "Connected User Experiences and Telemetry" service (default value)
# Включить службу "Функциональные возможности для подключенных пользователей и телеметрия" (значение по умолчанию)
# TelemetryService -Enable
```

this can be reduced to a one-liner

```
TelemetryServiceDisable 1 # "Connected User Experiences and Telemetry", default 1
```

the command name `TelemetryServiceDisable` already says what it does
so no more need to explain in comment
i only added the full name to make it extra clear

the commands should take boolean arguments (1 0 y n yes no true false)
and only use string parameters for multi-choice
so instead of adding/removing hashsigns (#) to comment/uncomment lines
we only need to change between 0 and 1

the transform should be simple enough for a regex replace, AST-transforms are probably overkill

also, please make separate scripts for english/russian/....
maybe use a build script to keep all scripts in sync

**Comment by cynodesmus** [comment]
Universality - always contains some redundancy.
For example: for me, a more detailed explanation is much more convenient. Especially when you are learning a script for the first time.
Also, my English is not good enough to ignore explanations in a more understandable language. If English requires a thoughtful reading of the text, then writing in the native language is acquired many times faster.

But, making several versions of scripts with different localizations is Sisyphean work for the author of the script. And the risk of introducing errors into one of the versions of the script is higher.
With the same success, you yourself can in your own version - delete unnecessary localizations. Moreover, now there is a GUI in which the necessary options can be marked with a mouse click.

**Comment by cynodesmus** [comment]
> the main script `Sophia.ps1` is unnecessarily verbose
> 
...

Universality - always contains some redundancy.
For example: for me, a more detailed explanation is much more convenient. Especially when you are learning a script for the first time.
Also, my English is not good enough to ignore explanations in a more understandable language. If English requires a thoughtful reading of the text, then writing in the native language is acquired many times faster.

But, making several versions of scripts with different localizations is Sisyphean work for the author of the script. And the risk of introducing errors into one of the versions of the script is higher.
With the same success, you yourself can in your own version - delete unnecessary localizations. Moreover, now there is a GUI in which the necessary options can be marked with a mouse click.

**Comment by farag2** [comment]
Графический интерфейс - это сильно сказано. :) Может, через полгода и доделаем нашу SophiApp.
