### ISSUE TITLE
Wonder if some security attributes are required on %SystemDrive%\Temp

### ISSUE THREAD

**Issue by gavenkoa** [farag2/Windows-10-Sophia-Script#93]
I see the change of `%TEMP%` to `%SystemDrive%\Temp` by:

```
New-Item -Path $env:SystemDrive\Temp -ItemType Directory -Force
```

But there is no any ACL settings around. Cannot tell which one should be set but incorrect settings are a potential security flaw.

**Comment by farag2** [comment]
Какие атрибуты нужны на папку?
