### ISSUE TITLE
Sophia script include virus code?

### ISSUE THREAD

**Issue by sysop200** [farag2/Windows-10-Sophia-Script#95]
When trying to download a repository, Defender swears at a virus:
Trojan:Win32/Spursint.F!cl
What is it?

**Comment by farag2** [comment]
1) Зачем скачивать весь репозиторий, если есть страница релизов?
2) На что конкретно ругается антивирус?
3) Нормальный антивирус пока что — только MS Defender (и он не параноит);
4) Троян, конечно, не распростроняю;
5) Думаю, что ругается на syspin. А если ругается на него, то в помойку такой антивирус.

**Comment by farag2** [comment]
Поставил я Chrome. В общем мои догадки подтвердились. Триггерится опять этот кусок браузера. В принципе Defender даже пишет, что ему не нравится.

```containerfile: D:\Downloads\Windows-10-Sophia-Script-master.zip
file: D:\Downloads\Windows-10-Sophia-Script-master.zip->Windows-10-Sophia-Script-master/Sophia/Sophia.psm1->(UTF-8)
webfile: D:\Downloads\Windows-10-Sophia-Script-master.zip|https://codeload.github.com/farag2/Windows-10-Sophia-Script/zip/master|pid:9636,ProcessStart:132502544691953655
```

https://github.com/farag2/Windows-10-Sophia-Script/blob/1301e1fc4d37acd25386b438ee5a7907c359bd1b/Sophia/Sophia.psm1#L7215

Думаю, все встало для тебя на место. Как прочтешь код, можешь сам закрыть.

**Comment by farag2** [comment]
Если реакции не будет, завтра закрою.
