### ISSUE TITLE
Pop-up image editor when print screen gone!

### ISSUE THREAD

**Issue by firstimpressionmusic** [farag2/Windows-10-Sophia-Script#96]
When taking screenshots, there used to be a pop up in the bottom right corner and it is gone,
Is there anyway to enable that again?

**Comment by farag2** [comment]
Enable what?

**Comment by firstimpressionmusic** [comment]
The pop up thing at the bottom right corner when take screen capture by pressing print screen,
![image](https://user-images.githubusercontent.com/48518681/99907306-1cb8f500-2d02-11eb-980b-2c59f1210950.png)

**Comment by firstimpressionmusic** [comment]
![image](https://user-images.githubusercontent.com/48518681/99907324-35c1a600-2d02-11eb-83c2-5c30d5c3c43a.png)

**Comment by farag2** [comment]
Why you want to enable it? I mean, is the pop-up no longer shown?

**Comment by firstimpressionmusic** [comment]
I installed it gain from 
https://www.microsoft.com/en-us/p/snip-sketch/9mz95kl8mr0l?activetab=pivot:overviewtab
Fixed now. Thanks!

**Comment by farag2** [comment]
Hm. As for me I've seen such a pop-up. That's why I'm curious.
Anyway, it's good, all have been fixed!
Good luck!
