### ISSUE TITLE
Disable Xbox Game Bar

### ISSUE THREAD

**Issue by firstimpressionmusic** [farag2/Windows-10-Sophia-Script#97]
I think you can disable Xbox Game bar in settings>Gaming

I see pop ups when launching games and  disabling fixes it, but it would be cool if its included in the script!

**Comment by farag2** [comment]
https://github.com/farag2/Windows-10-Sophia-Script/blob/b29e967897be0d623360dbff455c352b044a68a5/Sophia/Sophia.ps1#L886

:D
