### ISSUE TITLE
Desktop, Documents, Download Location

### ISSUE THREAD

**Issue by firstimpressionmusic** [farag2/Windows-10-Sophia-Script#98]
Can you add a path selector for these and not just the drive?

eg. D:\Folder1\Folder2\Desktop

**Comment by farag2** [comment]
Good idea. I can ask a user where he would like to move the user folders: to the SystemDrive or let him choose a folder.

**Comment by firstimpressionmusic** [comment]
You have that but it is always in the root drive, I have a seperate folder for those in mu hdd and I would like to  locate it to those 👍

**Comment by farag2** [comment]
Added into internal build. :)
