### ISSUE TITLE
After script ran - cannot update store apps & windows updates

### ISSUE THREAD

**Issue by etronics6** [farag2/Windows-10-Sophia-Script#99]
I update all windows update before running script, then when I run script I can no longer do updates, I do keep a couple of the store apps for clients & then try to update & it errors with code:  Windows Update Error 0x800705b4, it can be fixed by running the windows update troubleshooter, which is great, but thought you should know its causing an issues (at least I think it is) & hopefully in a future update it will be fixed.  Thank you for all you do, your script has helped me tremendously!!

**Comment by farag2** [comment]
Hello! You need just to reboot your PC. I know about that bug (aka feature). Faced many times.

**Comment by etronics6** [comment]
Ok great, thank you... sorry to bother u with the issues... I will try that next time I use!  Thanks again, you ROCK!!

**Comment by farag2** [comment]
:) Hope, I'll release the 5.3 release the next week.

**Comment by etronics6** [comment]
your the best!  I sent u a couple bucks on Ko-Fi... :-)

**Comment by farag2** [comment]
I see. Thanks. I'll resend to my coleague to keep coding futher. Hope, we'll release the first open alpha SophiApp in January. :)

**Comment by etronics6** [comment]
awesome!! I look forward to it!

**Comment by farag2** [comment]
We do too ))
https://www.sketch.com/s/f9ddbdcd-9fab-45d1-8b3e-2983dcecc9d3

**Comment by etronics6** [comment]
That looks amazing!  I am sure in english too... LOL :-)

**Comment by farag2** [comment]
For sure.
